from deep_translator import GoogleTranslator

def main_introduction()->str:
    print("City of Santa Rosa Tourist HelpDesk Chatbot")
    language: str = input("chatbot name: Pumili ng wika na nais | Choose your preferred language: Filipino or English: ").upper()
    functions: dict = {"FILIPINO": fil_introuction, "ENGLISH": en_introduction}
    while language not in functions:
        print("Ang wikang pinili ay wala sa aming system | The language you pick is not available in our system")
        language = input("Ilagay muli ang nais na wika | Enter again your preferred language: ").upper()

    functions[language]()  # Call the corresponding introduction
    return language  # Return the selected language
        
def en_introduction()->None:
    print("AskSantaRosa: Hi my name is AskSantaRosa")
    print("AskSantaRosa: You can ask me anything about the city of Santa Rosa")
    print("AskSantaRosa: Enter 'exit' to exit the program")

def fil_introuction()->None:
    print("AskSantaRosa: Kamusta ang pangalan ko ay AskSantaRosa")
    print("AskSantaRosa: Pwede mo kong tanungin ng tungkol sa bayan ng Santa Rosa")
    print("AskSantaRosa: I-type lamang ang 'exit' upang matapos ang program")

def user_input_EN()->str:
    question: str = input("user: ").upper()
    if question == 'EXIT':
        print("AskSantaRosa: Thank you for chatting with me!")
        return 'EXIT'
    return (question).upper()

def user_input_fil()->str:
    question: str = input("user: ").upper()
    if question == 'EXIT':
        print("AskSantaRosa: Salamat sa pakikipag-chat sa akin!")
        return 'EXIT'
    while True:
        try:
            translation = GoogleTranslator(source='tl', target='en').translate(question)
            translation.upper().strip()
            return translation
        except Exception as e:
            print(f"Nagkaroon ng error sa pag-translate: {e}")
            question = input("Ilagay muli ang tanong: ").upper()

def en_data()->dict:
    data = {
        "HOW ARE YOU": "Mabuti, Salamat sa pagtanong!",
        #History, Culture and General QUestion about Santa Rosa
        "INDUSTRIAL ESTATE WITHIN SANTA ROSA LAGUNA": "  Laguna Technopark Inc.\n\t\tGreenfield Automotive Park.\n\t\tToyota Special Economic Zone.\n\t\tLakeside Evozone Nuvali.\n\t\tDaystar Santa Rosa Industrial Park.\n\t\tSanta Rosa Commercial Complex.\n\t\tMeridian Industrial Complex.",
        "SCHOOL SCHOOLS WITHIN SANTA ROSA LAGUNA": "\n\t\tColegio de Santa Rosa de Lima\n\t\tThe Canossa School, Inc. City of Santa Rosa, Laguna\n\t\tQueen Anne School of Sta. Rosa \n\t\tBlessed Christian School de Sta. Rosa\n\t\tHoly Rosary College of Santa Rosa, Laguna, Inc.\n\t\tMaranatha Living Hope Academy \n\t\tDila Elementary School\n\t\tFaithful Grace Christian School\n\t\tSanta Rosa Science and Technology High School\n\t\tDominican College of Santa Rosa\n\t\tBalibago Integrated High School\n\t\tSaint Ruiz Montessori School\n\t\tGreen Fields Integrated School of Laguna, Inc.\n\t\tOur Lady of Fatima University Sta. Rosa, Laguna\n\t\tSts. Paul & Mark School Inc\n\t\tMarie Margarette School\n\t\tSouthville 4 National High School\n\t\tJesus The Exalted Name School\n\t\tSanta Rosa Elementary School Central I HACIENDA DOMINICANO\n\t\tPolytechnic University of Philippines",
        "SIKHAYAN FESTIVAL": "  Sikhayan Festival is a yearly cultural celebration in Santa Rosa City, Laguna, Philippines. It's a celebration of the city's founding and a way to honor the community's traditions and pride.",
        "SIKHAYAN FESTIVAL MEANS MEANING SIGNIFY SIGNIFIES SYMBOLIZE": "  Sikhayan is a Filipino word that means \"diligence\" and \"livelihood\". It is also the name of an annual festival in Santa Rosa, Laguna, Philippines. The festival celebrates the people of Santa Rosa, their entrepreneurial spirit, and their resilience.\n\t\tSikhayan Festival comes from sikap (hardwork) and kabuhayan (livelihood).",
        "HISTORY OF SIKHAYAN FESTIVAL": "  It was launched in 2000 by Mayor Leon Arcillas to celebrate the historic beginning of Santa Rosa City every year and a way to give recognition to it people, their resilience, and their entrepreneurial spirit that drive the city's continuous economic prosperity and growth.",
        "SANTA ROSA LAGUNA IS KNOWN FOR": "  Santa Rosa, Laguna is known for its industrial estates, theme park, and the Santa Rosa Arch.\n\t\tOne of the two largest municipalities in Laguna, Santa Rosa City, also known as the Lion City of the South, is located west of Laguna de Bay.\n\t\tSta Rosa was mainly known for the Coca-Cola and Toyota manufacturing plants in its industrial estates. More recently it has also become famous for being the site of Enchanted Kingdom, a local theme park, as well as several housing developments. Santa Rosa is also the exit travellers take along the South Luzon Expressway to go to Tagaytay and Taal Volcano. This city contains the 3rd largest complex in Laguna, Paseo de Santa Rosa.",
        "SANTA ROSA CITY CALLED THE LION CITY OF THE SOUTH": "  It is one of the Philippines’ fastest-growing economies. On March 10, 2004, the Philippine Congress approved Republic Act No. 9264, which made the city of Santa Rosa the first-class municipality from a fourth-class municipality. On July 10, 2004, Santa Rosa was proclaimed the country’s 101st city.\n\n\tThe city of Santa Rosa has made a name for itself in just three short years after it was transformed into a city and is now known for several economic triumphs. To put the City in the Billionaire’s Club among Philippine local government entities, the City’s 2007 income surpassed the one billion mark, from less than Php 600 million in 2003. Moreover, the flood of foreign and local investors interested in Santa Rosa has helped it treble its annual income during the last decade. Thus, making Santa Rosa the \“Lion City of the South.\”",
        "WHEN DID SANTA ROSA LAGUNA BECOME A CITY": "  It is one of the Philippines’ fastest-growing economies. On March 10, 2004, the Philippine Congress approved Republic Act No. 9264, which made the city of Santa Rosa the first-class municipality from a fourth-class municipality. On July 10, 2004, Santa Rosa was proclaimed the country’s 101st city.\n\n\tThe city of Santa Rosa has made a name for itself in just three short years after it was transformed into a city and is now known for several economic triumphs. To put the City in the Billionaire’s Club among Philippine local government entities, the City’s 2007 income surpassed the one billion mark, from less than Php 600 million in 2003. Moreover, the flood of foreign and local investors interested in Santa Rosa has helped it treble its annual income during the last decade. Thus, making Santa Rosa the \“Lion City of the South.\”",
        "TOTAL POPULATION OF SANTA ROSA LAGUNA": "  Its population as determined by the 2020 Census was 414,812. This represented 12.26% of the total population of Laguna province, or 2.56% of the overall population of the CALABARZON region.",
        "MEANING MEAN SIGNIFIES THE PLAZA IN SANTA ROSA LAGUNA": "\n\t\tThe plaza in Santa Rosa, Laguna, Philippines, symbolizes the city's history, culture, and heritage. The plaza features the Jose Rizal monument, which represents the city's martyrs and their fight for freedom.\n\nWhat does the square symbolize:\n\t\tHistory: The square was the place of execution of local guerrillas.\nCulture: The square is part of the Spanish-era city center of the city, which is being converted into a \"heritage square\".\n\t\tHeritage: The square is home to heritage houses and government offices.\n\t\tFreedom: The monument of Jose Rizal symbolizes the martyrs of the city and their fight for freedom.",
        "JOSE RIZAL MONUMENT MEANING SYMBOLIZE IN THE PLAZA OF SANTA ROSA LAGUNA": "  Martyrdom: The monument symbolizes the sacrifice of life for freedom.\n\t\tWisdom: The monument symbolizes the wisdom and bravery of the people of Santa Rosa.\n\t\tLight over darkness: The monument symbolizes the idea that light will always triumph over darkness.",
        "WHO ESTABLISHED THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINE SANTA ROSA CAMPUS": "  The Polytechnic University of the Philippines (PUP) Santa Rosa Campus was established by the Senate and House of Representatives of the Philippines through Republic Act No. 11784. This act is also known as the PUP-Santa Rosa Campus Act.",
        "WHO REQUESTED TO BUILD A BRANCH CAMPUS OF THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINES IN SANTA ROSA LAGUNA": "  The late mayor of Santa Rosa, Laguna, Hon. Leon C. Arcillas, requested the construction of the Polytechnic University of the Philippines (PUP) Santa Rosa Campus. The campus opened in 2003 and is considered a legacy of Arcillas's efforts to provide quality education to the residents of Santa Rosa and nearby towns.\n\t\tThe Polytechnic University of the Philippines was originally established as the Manila Business School in 1904. In 1978, the Philippine College of Commerce (PCC) was renamed PUP through Presidential Decree (PD) 1341.",
        "WHAT IS THE CHURCH'S NAME LOCATED BEHIND THE PLAZA OF SANTA ROSA LAGUNA": "  Santa Rosa de Lima Parish Church",
        "WHEN WAS THE SANTA ROSA DE LIMA PARISH CHURCH BUILT": "  The Santa Rosa de Lima Parish Church in Santa Rosa, Laguna, Philippines was established in 1792. The church was built by Spanish Catholic priest Francisco Favie.",
        "THE HISTORY OF THE SANTA ROSA DE LIMA PARISH CHURCH": "  The Santa Rosa de Lima Parish Church in Santa Rosa, Laguna, Philippines was built in 1792 by Spanish Catholic priest Francisco Favie. The church was named after Saint Rose of Lima, the patron saint of the Philippines, America, and the East Indies.\n\nConstruction:\n\t\tThe church and convent were built within 12 years\n\t\tThe present church building was constructed in 1796 by Spanish friars with help from Chinese laborers\n\t\tThe church was blessed on August 4, 1812\n\t\tThe first Mass was held on August 30, 1812\n\nHistory:\n\t\tBefore the church was built, the area was called \"Bucol\"\n\t\tThe residents changed the name of the area to \"Santa Rosa\" in honor of the patron saint\n\t\tThe original structure still stands and is now known as Museo de Santa Rosa\n\nSaint Rose of Lima\n\t\tSaint Rose of Lima was born Isabel Flores de Oliva in Lima, Peru in 1586\n\t\tShe was known for helping the sick and hungry in her community\n\t\tShe was given the name Rose by a housemaid who said she was \"as lovely as a rose\"",
        "HISTORICAL TIMELINE OF SANTA ROSA LAGUNA": "  The historical timeline of Santa Rosa, Laguna, Philippines includes the Spanish colonization, the Philippine Revolution, and the post-war era.\n\t\t1571: Spanish Conquistador Juan de Salcedo discovers Biñan and annexes it to Tabuco\n\t\t1688: Barrio Bukol separates from Cabuyao\n\t\t1792: Barrio Bukol becomes the municipality of Santa Rosa\n\t\t1812: The Saint Rose of Lima Parish Church is blessed\n\t\t1859–1860: The Santa Rosa Arch is built to replace a Spanish guard tower\n\t\t1898: Santa Rosa plays a key role in the Philippine Revolution against Spain and signs the Act of Independence\n\t\t1945: Santa Rosa is liberated from Japanese occupation during World War II\n\t\t1970s: The economy of Santa Rosa is based on agriculture and family-owned businesses\n\t\t1980s: Industrialization and foreign investment transform Santa Rosa's economy and society\n\t\t2004: Santa Rosa becomes a city",
        "HISTORICAL HISTORY BACKGROUND OF SANTA ROSA LAGUNA": "  Santa Rosa, Laguna, Philippines has a rich history that includes its role in the Philippine Revolution, its time under Japanese occupation, and its development from an agricultural town to a modern city.\n\nEarly history\n\t\tBarrio Bukol\n\t\tIn 1688, Barrio Bukol separated from Cabuyao and became part of Biñan.\n\nSaint Rose of Lima Parish Church\n\t\tIn 1792, the Spanish Catholic priest Francisco Favie built the Saint Rose of Lima Parish Church.\n\nMunicipality of Santa Rosa\n\t\tIn 1792, Barrio Bukol became its own municipality and was named after Saint Rose of Lima.\n\nSanta Rosa's role in the Philippine Revolution\n\t\tSanta Rosa was a key site in the Philippine Revolution against the Spanish. In 1898, Santa Rosa signed the Act of Independence, which proclaimed Philippine Independence from Spain.\n\nWorld War II\n\t\tJapanese occupation: During World War II, the Japanese briefly occupied Santa Rosa.",
        "WHAT CALABARZON MEANS MEANING OF": "  Calabarzon is the name of an administrative region in the Philippines that's made up of five provinces: Cavite, Laguna, Batangas, Rizal, and Quezon. The name is an acronym of the first letter of each province.",
        "WHY IS IT CALLED CALABARZON": "  The region was created to integrate the social and economic development of the five provinces.\n\t\tIt's also known as Region IV-A.",
        "IN WHAT ASPECT IS CALABARZON KNOWN": "Calabarzon is known as the industrial powerhouse of the Philippines.\n\t\tIt's home to many of the country's most densely populated provinces.\n\t\tIt's the birthplace of Philippine independence from Spain in 1898.\n\t\tIt's the birthplace of national heroes like Jose Rizal.\n\t\tIt's home to many cultural traditions, including wood carving and taka (papier-mâché).",
        "WHAT IS THE RANKING POSITION OF SANTA ROSA LAGUNA WHEN IT COMES TO ITS RANKING AMONG NEARBY CITIES IN THE ENTIRE COUNTRY": "  Santa Rosa, Laguna is a prominent city in the Philippines, and is considered the richest city in Luzon outside of Metro Manila. It is also one of the fastest-growing economies in the country.\n\nRanking:\n\t\tIn 2019, Santa Rosa was ranked third in the country for its collection efficiency of locally sourced revenues.\n\t\tIn 2022, Santa Rosa had the highest revenue of any local government unit (LGU) in Laguna.",
        "WHERE WAS DR. JOSE RIZAL BORN": "Calamba, Laguna",
        "WHEN WAS DR. JOSE RIZAL BORN": "June 19, 1861",
        "WHAT IS THE FULL NAME OF DR. JOSE RIZAL": "  Jose Protacio Rizal Mercado y Alonso Realonda",
        "WHO ARE THE PARENTS OF DR. JOSE RIZAL": "  Francisco Mercado and Teodora Alonso Realonda",
        "WHO IS THE FATHER OF DR. JOSE RIZAL": "  Francisco Mercado ",
        "WHO IS THE MOTHER OF DR. JOSE RIZAL": "  Teodora Alonso Realonda",
        #Attractions/ tourist destination in Santa Rosa
        "NATURE NATURAL ATTRACTION IN LAGUNA": "  Pagsanjan Falls\n\t\tHulugan Falls\n\t\tHidden Valley Falls\n\t\tTaytay Falls\n\t\tLake Pandin\n\t\tMount Makiling\n\t\tSampaloc Lake\n\t\tMt. Banahaw\n\t\tLake Yambo\n\t\tBangking Kahoy Valley\n\t\tLake Caliraya\n\t\tMakiling Botanic Gardens\n\t\tBukal Falls\n\t\tJapanese Garden\n\t\tDalitiwan River\n\t\tPanguil River Eco Park\n\t\tMount Kalisungan\n\t\tCavinti Underground River and Caves Complex\n\t\tTayak Hill\n\t\tBunga Falls\n\t\tMt. Romelo\n\t\tBuntot Palos Falls\n\t\tKalayaan Twin Falls\n\t\tBuruwisan Falls\n\t\tPueblo El Salvador Nature’s Park and Picnic Grove\n\t\tMagdalena White Water River\n\t\tLake Palakpakin\n\t\tLake Calibato\n\t\tLake Bunot\n\t\tLake Muhikap\n\t\tHilabaan Island",
        "HISTORICAL PLACES IN SANTA ROSA LAGUNA": "  Cuartel De Sto. Domingo\n\t\tSanta Rosa De Lima Parish Church\n\t\tMuseo De Santa Rosa\n\t\tCity Plaza\n\t\tSanta Rosa Arch",
        "LOCAL HERITAGE IN BIÑAN LAGUNA": "  Site of Historic Alberto Mansion\n\t\tSentrong Pangkultura ng Biñan (Old Municipal Building)\n\t\tSchool of Rizal Site and Museum\n\t\tSan Isidro Labrador Catholic Church\n\t\tVicente Ocampo House\n\t\tJose Rizal Monument\n\t\tLos Maduros Bandstand\n\t\tFrancisco Almeda House\n\t\tCasa Biñanese – Jacobo Gonzales House\n\t\tJacinto Francisco House\n\t\tFilomena Belizario Hernandez House\n\t\tAlberto Yaptinchay House\n\t\tPedro-Isidro Cariño Isidro House\n\t\tIluminado Valencia House\n\t\tBiñan Roman Catholic Cemetery Camposanto\n\t\tCasa Paroquial-Biñan Cursillo House\n\t\tGabaldon Building of Biñan Elementary School\n\t\tCapilla De San Jose\n\t\tOld Binyang PNR Station including its Office and Railway\n\t\tBiñan Municipal Cemetery\n\t\tFrancisco Baylon House\n\t\tFrancisco Guico House\n\t\tTeodora Velasco House\n\t\tLaureano Cariño House\n\t\tIsisdro Gonzalez House\n\t\tSoro-soro Prinza Dam\n\t\tHistoric Alberto Mansion",
        "BARANGAYS IN SANTA ROSA LAGUNA": "  There are eighteen (18) baranggays that can be found in Santa Rosa, Laguna. The following are the eighteen (18) baranggays:\n\t\tAplaya\n\t\tBalibago\n\t\tCaingin\n\t\tDila\n\t\tDita\n\t\tDon Jose\n\t\tIbaba\n\t\tKanluran\n\t\tLabas\n\t\tMacabling\n\t\tMalitlit\n\t\tMalusak\n\t\tMarket Area\n\t\tPooc\n\t\tPulong Santa Cruz\n\t\tSanto Domingo\n\t\tSinalhan\n\t\tTagapo",
        "WHAT ARE THE ATTRACTIONS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN SANTA ROSA, LAGUNA": "  Santa Rosa City have many attractions that can surely bring happiness not just to tourists, but also to its citizens. These are the attractions, that the Lion City of the South — Santa Rosa, Laguna, can offer:\n\n\t\tTheme Park\n\t\tEnchanted Kingdom\n\n\t\tShopping Centers\n\t\tSM City Santa Rosa\n\t\tRobinson's Mall\n\t\tAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\n\t\tWalterMart\n\t\tVictory Mall\n\t\tTarget Mall\n\t\tWest Borrough Town Center\n\t\tPaseo de Santa Rosa\n\t\tEton City Square\n\n\t\tFarms\n\t\tFun Farm at Sta. Elena\n\t\tHoly Carabao\n\nParks\n\t\tNuvali Park\n\t\tSanta Rosa's City Plaza\n\n\t\tResorts and Events Place\n\t\tDictado 1\n\t\tDictado 2\n\t\tDictado 3\n\t\tSouthpick Resort\n\t\tCalypso Resort Hotel\n\t\tCarvill Private Resort\n\t\tCesar's Cabin Private Resort\n\t\tCriselda Private Resort\n\t\tPopong's Bukid Private Resort\n\t\tOlive's Private Resort\n\t\tBayani Resort\n\t\tKyler and Kean Private Resort\n\t\tCasa Vallejo Events Place and Private Resort\n\t\tNMV Resort Farmview\n\t\tLas Asturias\n\t\tVilla Gilda Resort\n\t\tSherinai Events Place\n\t\tSouth Country Garden\n\t\tLouLyn's Resort\n\t\tPablo's Events Place\n\t\tMarigold's Farm Resort\n\t\tTAR's Family and  Private Resort\n\t\tBay View Resort\n\n\t\tHotels / Motels\n\t\tSeda Nuvali\n\t\tPaseo Premiere Hotel\n\t\tAsiatel Inn\n\t\tTechopark Hotel\n\t\tMicrotel\n\t\tEl Cielito Hotel\n\t\tCasa Emerita\n\t\tCandy Motel\n\t\tHotel Sogo\n\t\tMariposa Hotel\n\nOthers(Sta. Elena's Golf and Country Club)",
        "SHOPPING MALLS IN SANTA ROSA LAGUNA": "  These are the list of Santa Rosa's thriving Shopping Centers:\n\t\tSM City Santa Rosa\n\t\tRobinson's Mall\n\t\tAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\n\t\tWalterMart\n\t\tVictory Mall\n\t\tTarget Mall\n\t\tWest Borrough Town Center\n\t\tPaseo de Santa Rosa\n\t\tEton City Square",
        "RESORTS AND EVENTS PLACE IN SANTA ROSA LAGUNA": "  There are numerous private, and public resorts, and events place in Santa Rosa, and these includes:\n\t\tSouthpick Resort\n\t\tDictado 1\n\t\tDictado 2\n\t\tDictado 3\n\t\tCalypso Resort Hotel\n\t\tCarvill Private Resort\n\t\tCesar's Cabin Private Resort\n\t\tCriselda Private Resort\n\t\tPopong's Bukid Private Resort\n\t\tOlive's Private Resort\n\t\tKyler and Kean Private Resort\n\t\tCasa Vallejo Events Place and Private Resort\n\t\tNMV Resort Farmview\n\t\tLas Asturias\n\t\tVilla Gilda Resort\n\t\tBayani Resort\n\t\tSherinai Events Place\n\t\tSouth Country Garden\n\t\tLouLyn's Resort\n\t\tPablo's Events Place\n\t\tMarigold's Farm Resort\n\t\tTAR's Family and  Private Resort\n\t\tBay View Resort",
        "PARKS IN SANTA ROSA LAGUNA": "  Currently, there are two (2) available parks in Santa Rosa, and these are what follows:\n\t\tNuvali Park\n\t\tSanta Rosa's City Plaza",
        "THEME PARK IN SANTA ROSA": "  Enchanted Kingdom, also known as EK, is the only theme park that can be found in Santa Rosa, it is known for numerous fun and nerve-wracking rides it can offer, as well as the developed lot spaces it occupies.",
        #Lodging Area in Santa Rosa
        "HOTELS OR MOTELS IN SANTA ROSA": "  These are some of the Hotels, or Motels, that are famous, in the City:\n\t\tSeda Nuvali\n\t\tPaseo Premiere Hotel\n\t\tAsiatel Inn\n\t\tTechopark Hotel\n\t\tMicrotel\n\t\tEl Cielito Hotel\n\t\tCasa Emerita\n\t\tCandy Motel\n\t\tHotel Sogo\n\t\tMariposa Hotel",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY POOC": "  In total, there are five (5) resorts located in Barangay Pooc, and these are what follows:\n\t\tCarvill Private Resort\n\t\tCriselda Private Resort\n\t\tPopong's Bukid Private Resort\n\t\tOlive's Private Resort\n\t\tKyler and Kean Private Resort\n\n\t\tThe mentioned resorts, are all located in  Caramay Compound, La Concordia, Barangay Pooc, City of Santa Rosa, Laguna.",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY MARKET AREA": "  Barangay Market Area have five(5) resorts can offer, and these are:\n\t\tSouthpick Resort\n\t\tPablo's Events Place\n\t\tDictado 1\n\t\tDictado 2\n\t\tDictado 3",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY SINALHAN": "  Currently, There are no resorts that can be found in Barangay Sinalhan",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY TAGAPO": "  These are the resort Barangay Tagapo can offer:\n\t\tLouLyn's Resort\n\t\tTAR's Family and Private Resort\n\t\tNMV Resort\n\t\tSherinai Events Place\n\t\tMarigold's Farm Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY IBABA": "  These is the only resort Barangay Ibaba can offer:\n\t\tCasa Vallejo Events Place and Private Resort",
        "RESORTS THAT CAN FOUND LOCATE LOCATED LOCATION OF IN BARANGAY CAINGIN": "  These are the only resorts Barangay Caingin can offer:\n\t\tVilla Gilda Resort\n\t\tBayani Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY DITA": "  These is the only resort that can be found in Barangay Dita:\n\t\tSouth Country Garden",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED IN BARANGAY MACABLING": "  The only resort that can be found in Barangay Macabling is:\n\t\tCalypso Resort ",
        # Emergency Services in Santa Rosa
        "EMERGENCY CLINICS MEDICAL AID HOSPITALS IN SANTA ROSA": "  St. James Hospital\n\t\tSanta Rosa Community Hospital\n\t\tNew Sinai MD Hospital\n\t\tThe Medical City South Luzon\n\t\tUnihealth Santa Rosa Hospital and Medical Center\n\t\tMarian Hospital\n\t\tCity Medic Emergency Hospital\n\t\tBalibago Polyclinic and Hospital, Inc.\n\t\tSanta Rosa Hospital and Medical Center\n\t\tHealthway QualiMed Hospital Santa Rosa\n\t\tThe Medical City, South Luzon",
        "FIND AREA LOCATED LOCATION OF ST. JAMES HOSPITAL": "The location of St. James Hospital is Brgy. Dita, JP. Rizal Street, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF ST. JAMES HOSPITAL": "  These are the accessible contact/ hotline numbers, and email address of St. James Hospital: \n\t\tLine Numbers: 0933-825-6214\n\t\t\t      (02)8584-4533\n\t\t\t      (049)534-1254\n\t\t\t      (049)502-0058",
        "FIND AREA LOCATED LOCATION OF NEW SINAI MDI HOSPITAL":"The location of New Sinai MDI Hospital is National Highway, Brgy Tagapo, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF NEW SINAI MDI HOSPITAL": "  These are the accessible contact/ hotline number of New Sinai MDI Hospital\n\t\tLine Number: 0917-180-6534",
        "FIND AREA LOCATED LOCATION OF SANTA ROSA COMMUNITY HOSPITAL":"The location of Santa Rosa Community Hospital is LM Subdivision, Brgy. Market Area, Cattleya St. City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF SANTA ROSA COMMUNITY HOSPITAL": "  These are the accessible contact/ hotline number of Santa Rosa Community Hospital\n\t\tLine Number: 0950-666-8525",
        "FIND AREA LOCATED LOCATION OF MEDICAL CITY SOUTH LUZON":"The location of Medical City South Luzon is Greenfield City, Brgy. Don Jose, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF MEDICAL CITY SOUTH LUZON": "  These are the accessible contact/ hotline number of Medical City of South Luzon\n\t\tLine Number: (049)303-3000\n\t\t\t      (639)20-981-4454\n\t\tEmail: tmcsl.customercare@themedicalcity.com",
        "FIND AREA LOCATED LOCATION OF UNIHEALTH-SANTA ROSA":"The location of Unihealth-Santa Rosa is RSBS Blvd., San Lorenzo South, Brgy. Balibago, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF UNIHEALTH-SANTA ROSA": "  These are the accessible contact/ hotline number of Medical City of South Luzon\n\t\tLine Number: (+63)999-880-7519\n\t\t\t      (+63)917-825-2335\n\t\tEmail: starosamed08@gmail.com",
        "FIND AREA LOCATED LOCATION OF MARIAN HOSPITAL":" The location of Marian Hospital is Rizal Blvd., Brgy. Tagapo, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF MARIAN HOSPITAL": "  These are the accessible contact/ hotline number of Marian Hospital\n\t\tLine Number: (02)8584-4483",
        "FIND AREA LOCATED LOCATION OF CITY MEDIC EMERGENCY HOSPITAL": "The location of City Medic Emergency Hospital is Rizal Blvd., Brgy. Tagapo, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF CITY MEDIC EMERGENCY HOSPITAL": "  These are the accessible contact/ hotline number of City Medic Emergency Hospital:\n\t\tLine Number: 09671134164",
        "FIND AREA LOCATED LOCATION OF BALIBAGO POLYCLINIC AND HOSPITAL INC.": "The location of Balibago Polyclinic and Hospital Inc is Rizal Blvd., Brgy. Balibago, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF BALIBAGO POLYCLINIC AND HOSPITAL INC.": "  These are the accessible contact/ hotline number of Balibago Polyclinic Hospital:\n\t\tLine Number: 09106703156",
        "FIND AREA LOCATED LOCATION OF SANTA ROSA MEDICAL AND HOSPITAL CENTER": "The location of Santa Rosa Medical and Hospital Center  is Brgy. Balibago, San Lorenzon Rd, City of Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF SANTA ROSA MEDICAL AND HOSPITAL CENTER": "  These are the accessible contact/ hotline number of Santa Rosa Medical and Hospital center:\n\t\tLine Number: 09106703156",
        "FIND AREA LOCATED LOCATION OF HEALTHWAY QUALIMED HOSPITAL SANTA ROSA": " The location of Healthway QualiMed Hospital Santa Rosa is Brgy. Sto. Domingo, , Nuvali North, West Nature Ave.,, City of Santa Rosa Laguna", 
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF HEALTHWAY QUALIMED HOSPITAL SANTA ROSA": "  These are the accessible contact/ hotline number of Healthway Qualimed Hospital Santa Rosa:\n\t\tLine Number: 09174662273\n\t\t\t     (02)7777-2273",
        #Transportation in Santa Rosa
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBBL Bus Terminal\n\t\tBalibago - Sta. Cruz Van Terminal\n\t\tBalibago Transport Terminal - Sta. Rosa\n\t\tAlabang Express Jeepney Terminal\n\t\tShuttle Service Terminal\n\t\tVan terminal\n\t\tJAM Bus Terminal\n\t\tPaseo De StaRosa\n\t\tUBE Express - Robinsons Sta. Rosa\n\t\tJam Liner Bus Stop\n\t\tTodap Terminal\n\t\tBBPL Transport Terminal\n\t\tBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\n\t\tPaseo de Sta Rosa - Calamba Jeepney Terminal\n\t\tJam Transit Inc. Terminal - Penta\n\t\tTricycle terminal\n\t\tHM Terminal-Target\n\t\tNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A JEEPNEY TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tBalibago Transport Terminal - Sta. Rosa\n\t\tAlabang Express Jeepney Terminal\n\t\tPaseo De StaRosa\n\t\tBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\n\t\tPaseo de Sta Rosa - Calamba Jeepney Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A BUS TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBBL Bus Terminal\n\t\tShuttle Service Terminal\n\t\tJAM Bus Terminal\n\t\tUBE Express - Robinsons Sta. Rosa\n\t\tJam Liner Bus Stop\n\t\tBBPL Transport Terminal\n\t\tJam Transit Inc. Terminal - Penta\n\t\tHM Terminal-Target\n\t\tNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A VAN TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBalibago - Sta. Cruz Van Terminal\n\t\tBalibago Transport Terminal - Sta. Rosa\n\t\tShuttle Service Terminal\n\t\tVan terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TRICYCLE TERMINAL": "  Paseo De StaRosa\n\t\tTodap Terminal\n\t\tTricycle terminal"
        }
    return data

def fil_data()->dict:
    data = {
        "HOW ARE YOU": "Mabuti, Salamat sa pagtanong!",
        #History, Culture and General QUestion about Santa Rosa
        "INDUSTRIAL ESTATE WITHIN SANTA ROSA LAGUNA": "  Laguna Technopark Inc.\n\t\tGreenfield Automotive Park.\n\t\tToyota Special Economic Zone.\n\t\tLakeside Evozone Nuvali.\n\t\tDaystar Santa Rosa Industrial Park.\n\t\tSanta Rosa Commercial Complex.\n\t\tMeridian Industrial Complex.",
        "SCHOOL SCHOOLS WITHIN SANTA ROSA LAGUNA": "  Colegio de Santa Rosa de Lima\n\t\tThe Canossa School, Inc. City of Santa Rosa, Laguna\n\t\tQueen Anne School of Sta. Rosa\n\t\tBlessed Christian School de Sta. Rosa\n\t\tHoly Rosary College of Santa Rosa, Laguna, Inc.\n\t\tMaranatha Living Hope Academy\n\t\tDila Elementary School\n\t\tFaithful Grace Christian School\n\t\tSanta Rosa Science and Technology High School\n\t\tDominican College of Santa Rosa\n\t\tBalibago Integrated High School\n\t\tSaint Ruiz Montessori School\n\t\tGreen Fields Integrated School of Laguna, Inc.\n\t\tOur Lady of Fatima University Sta. Rosa, Laguna\n\t\tSts. Paul & Mark School Inc\n\t\tMarie Margarette School\n\t\tSouthville 4 National High School\n\t\tJesus The Exalted Name School\n\t\tSanta Rosa Elementary School Central I HACIENDA DOMINICANO\n\t\tPolytechnic University of Philippines",
        "SIKHAYAN FESTIVAL": "  Ang Sikhayan Festival ay isang taunang pagdiriwang ng kultura sa Lungsod ng Santa Rosa, Laguna, Pilipinas. Ito ay isang pagdiriwang ng pagkakatatag ng lungsod at isang paraan upang parangalan ang mga tradisyon at pagmamalaki ng komunidad.",
        "SIKHAYAN FESTIVAL MEANS MEANING OF SIGNIFY SIGNIFIES": "  Ang Sikhayan ay isang salitang Filipino na nangangahulugang \"sipag\" at \"kabuhayan\". Ito rin ang pangalan ng taunang pagdiriwang sa Santa Rosa, Laguna, Pilipinas. Ipinagdiriwang ng pagdiriwang ang mga tao ng Santa Rosa, ang kanilang espiritu ng pagnenegosyo, at ang kanilang katatagan.\n\t\tAng Sikhayan Festival ay nagmula sa sikap (hardwork) at kabuhayan (kabuhayan)",
        "THE HISTORY OF SIKHAYAN FESTIVAL": "  Ito ay inilunsad noong 2000 ni Mayor Leon Arcillas upang ipagdiwang ang makasaysayang simula ng Santa Rosa City bawat taon at isang paraan upang bigyan ng pagkilala ang mga tao, ang kanilang katatagan, at ang kanilang entrepreneurial spirit na nagtutulak sa patuloy na kaunlaran at paglago ng ekonomiya ng lungsod.",
        "SANTA ROSA LAGUNA IS KNOWN FOR": "  Ang Santa Rosa, Laguna ay kilala sa mga pang-industriyang estate nito, theme park, at Santa Rosa Arch.\n\t\tIsa sa dalawang pinakamalaking munisipalidad sa Laguna, ang Santa Rosa City, na kilala rin bilang Lion City of the South, ay matatagpuan sa kanluran ng Laguna de Bay.\n\t\tAng Sta Rosa ay pangunahing kilala para sa Coca-Cola at Toyota manufacturing plants sa mga industriyal na estate nito. Kamakailan ay naging sikat din ito sa pagiging site ng Enchanted Kingdom, isang lokal na theme park, pati na rin ang ilang pagpapaunlad ng pabahay. Ang Santa Rosa din ang exit traveller na dadaan sa South Luzon Expressway para pumunta sa Tagaytay at Taal Volcano. Ang lungsod na ito ay naglalaman ng ika-3 pinakamalaking complex sa Laguna, Paseo de Santa Rosa.",
        "WHY IS SANTA ROSA CITY CALLED THE LION CITY OF THE SOUTH": "  It is one of the Philippines’ fastest-growing economies. On March 10, 2004, the Philippine Congress approved Republic Act No. 9264, which made the city of Santa Rosa the first-class municipality from a fourth-class municipality. On July 10, 2004, Santa Rosa was proclaimed the country’s 101st city.\n\n\t\tThe city of Santa Rosa has made a name for itself in just three short years after it was transformed into a city and is now known for several economic triumphs. To put the City in the Billionaire’s Club among Philippine local government entities, the City’s 2007 income surpassed the one billion mark, from less than Php 600 million in 2003. Moreover, the flood of foreign and local investors interested in Santa Rosa has helped it treble its annual income during the last decade. Thus, making Santa Rosa the \“Lion City of the South.\”",
        "WHEN DID SANTA ROSA LAGUNA BECOME A CITY": "  Isa ito sa pinakamabilis na lumalagong ekonomiya ng Pilipinas. Noong Marso 10, 2004, inaprubahan ng Kongreso ng Pilipinas ang Republic Act No. 9264, na nagtaas sa Santa Rosa mula sa isang ika-apat na klaseng bayan patungo sa unang klaseng lungsod. Noong Hulyo 10, 2004, idineklara ang Santa Rosa bilang ika-101 na lungsod ng bansa.\n\n\t\tNakilala ang lungsod ng Santa Rosa sa loob lamang ng tatlong taon matapos itong gawing lungsod at kilala na ngayon sa ilang mga tagumpay sa ekonomiya. Upang mailagay ang Lungsod sa Billionaire's Club sa mga lokal na pamahalaan ng Pilipinas, nalampasan ng kita nito noong 2007 ang isang bilyon, mula sa mas mababa sa Php 600 milyon noong 2003. Bukod pa rito, ang dagsa ng mga banyaga at lokal na mamumuhunan na interesado sa Santa Rosa ay nakatulong upang mapataas ng tatlong beses ang taunang kita nito sa nagdaang dekada. Kaya naman, tinawag ang Santa Rosa na \"Lion City of the South.\"",
        "TOTAL POPULATION OF SANTA ROSA LAGUNA": "  Ang populasyon nito batay sa Census noong 2020 ay 414,812. Ito ay kumakatawan sa 12.26% ng kabuuang populasyon ng lalawigan ng Laguna, o 2.56% ng kabuuang populasyon ng rehiyon ng CALABARZON.",
        "WHAT SIGNIFIES THE PLAZA IN SANTA ROSA LAGUNA": "  Ang plaza sa Santa Rosa, Laguna, Pilipinas, ay sumisimbolo sa kasaysayan, kultura, at pamana ng lungsod. Ang plaza ay nagtatampok ng monumento ni Jose Rizal na kumakatawan sa mga martir ng lungsod at ang kanilang pakikibaka para sa kalayaan.\n\n\t\tAno ang sinisimbolo ng plaza:\n\t\tKasaysayan: Ang plaza ay lugar ng pagbitay sa mga lokal na gerilya.\n\t\tKultura: Bahagi ang plaza ng sentrong kolonyal na Espanyol na ginagawang \"heritage square.\"\n\t\tPamana: Narito ang mga makasaysayang bahay at tanggapan ng pamahalaan.\n\t\tKalayaan: Ang monumento ni Jose Rizal ay sumasagisag sa mga martir ng lungsod at ang kanilang pakikibaka para sa kalayaan.",
        "WHAT DOES THE JOSE RIZAL MONUMENT SYMBOLIZE IN THE PLAZA OF SANTA ROSA LAGUNA": "  Martiryo: Ang monumento ay sumasagisag sa pagsasakripisyo ng buhay para sa kalayaan.\n\t\tKarunungan: Ang monumento ay sumasagisag sa karunungan at katapangan ng mga taga-Santa Rosa.\n\t\tLiwanag laban sa kadiliman: Ang monumento ay sumasagisag sa ideya na ang liwanag ay laging mananaig sa kadiliman.",
        "WHO ESTABLISHED THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINE-SANTA ROSA CAMPUS": "  Itinatag ang Polytechnic University of the Philippines (PUP) Santa Rosa Campus ng Senado at Kapulungan ng mga Kinatawan ng Pilipinas sa pamamagitan ng Republic Act No. 11784. Kilala rin ang batas na ito bilang PUP-Santa Rosa Campus Act.",
        "WHO REQUESTED TO BUILD A BRANCH CAMPUS OF THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINES IN SANTA ROSA, LAGUNA": "  Ang yumaong alkalde ng Santa Rosa, Laguna, Kgg. Leon C. Arcillas, ang humiling ng pagtatayo ng Polytechnic University of the Philippines (PUP) Santa Rosa Campus. Binuksan ang kampus noong 2003 at itinuturing na pamana ng mga pagsisikap ni Arcillas upang magbigay ng de-kalidad na edukasyon sa mga residente ng Santa Rosa at mga kalapit na bayan.\n\t\tOrihinal na itinatag ang Polytechnic University of the Philippines bilang Manila Business School noong 1904. Noong 1978, pinalitan ang pangalan ng Philippine College of Commerce (PCC) bilang PUP sa bisa ng Presidential Decree (PD) 1341.",
        "CHURCH'S NAME LOCATED BEHIND THE PLAZA OF SANTA ROSA LAGUNA": "  Santa Rosa de Lima Parish Church",
        "WHEN WAS THE SANTA ROSA DE LIMA PARISH CHURCH BUILT": "  Ang Santa Rosa de Lima Parish Church sa Santa Rosa, Laguna, Pilipinas ay itinatag noong 1792. Itinayo ito ng paring Katolikong Kastila na si Francisco Favie.",
        "THE HISTORY OF THE SANTA ROSA DE LIMA PARISH CHURCH": "  Ang Santa Rosa de Lima Parish Church sa Santa Rosa, Laguna, Pilipinas ay itinayo noong 1792 ng paring Katolikong Kastila na si Francisco Favie. Ipinangalan ang simbahan kay Santa Rosa ng Lima, ang patrona ng Pilipinas, Amerika, at Silangang Indiya.\n\n\t\tPagkakatayo:\n\t\tAng simbahan at kumbento ay itinayo sa loob ng 12 taon\n\t\tAng kasalukuyang gusali ng simbahan ay itinayo noong 1796 ng mga paring Kastila na tumulong ang mga Tsinong manggagawa\n\t\tAng simbahan ay binasbasan noong Agosto 4, 1812\n\t\tAng unang Misa ay ginanap noong Agosto 30, 1812\n\n\t\tKasaysayan:\n\t\tBago itinayo ang simbahan, ang lugar ay tinawag na \"Bucol\"\n\t\tPinalitan ng mga residente ang pangalan ng lugar bilang \"Santa Rosa\" bilang parangal sa patrona\n\t\tAng orihinal na istruktura ay nananatili at kilala na ngayon bilang Museo de Santa Rosa\n\n\t\tSanta Rosa ng Lima\n\t\tSi Santa Rosa ng Lima ay ipinanganak bilang Isabel Flores de Oliva sa Lima, Peru noong 1586\n\t\tNakilala siya sa pagtulong sa mga may sakit at nagugutom sa kanyang komunidad\n\t\tBinigyan siya ng pangalang Rose ng isang kasambahay na nagsabing siya ay \"singganda ng isang rosas\"",
        "HISTORICAL TIMELINE OF SANTA ROSA LAGUNA": "  Ang makasaysayang timeline ng Santa Rosa, Laguna, Philippines ay kinabibilangan ng pananakop ng mga Espanyol, ang Himagsikang Pilipino, at ang panahon pagkatapos ng digmaan.\n\t\t1571: Natuklasan ng Espanyol na Conquistador na si Juan de Salcedo ang Biñan at isinama ito sa Tabuco\n\t\t1688: Nahiwalay ang Barrio Bukol mula sa Cabuyao\n\t\t1792: Naging munisipyo ang Barrio Bukol bilang Santa Rosa\n\t\t1812: Pinagpala ang Saint Rose of Lima Parish Church\n\t\t1859–1860: Itinayo ang Santa Rosa Arch upang palitan ang isang Espanyol na guard tower\n\t\t1898: Nagampanan ng Santa Rosa ang isang mahalagang papel sa Himagsikang Pilipino laban sa Espanya at lumagda sa Act of Independence\n\t\t1945: Nalaya ang Santa Rosa mula sa pananakop ng Hapon noong World War II\n\t\t1970s: Ang ekonomiya ng Santa Rosa ay nakabatay sa agrikultura at mga negosyong pag-aari ng pamilya\n\t\t1980s: Ang industriyalisasyon at pamumuhunan ng mga dayuhan ay nagbago sa ekonomiya at lipunan ng Santa Rosa\n\t\t2004: Naging lungsod ang Santa Rosa",
        "HISTORICAL HISTORY BACKGROUND OF SANTA ROSA LAGUNA": "  Ang Santa Rosa, Laguna, Philippines ay may mayamang kasaysayan na kinabibilangan ng papel nito sa Himagsikang Pilipino, ang panahon nito sa ilalim ng pananakop ng Hapon, at ang pag-unlad nito mula sa isang bayang agrikultural patungo sa isang modernong lungsod.\n\n\t\tMaagang kasaysayan\n\t\tBarrio Bukol\n\t\tNoong 1688, nahiwalay ang Barrio Bukol mula sa Cabuyao at naging bahagi ng Biñan.\n\n\t\tSaint Rose of Lima Parish Church\n\t\tNoong 1792, itinayo ng Espanyol na pari na si Francisco Favie ang Saint Rose of Lima Parish Church.\n\n\t\tMunicipality of Santa Rosa\n\t\tNoong 1792, naging sariling munisipyo ang Barrio Bukol at pinangalanan ito bilang Santa Rosa bilang parangal kay Saint Rose of Lima.\n\n\t\tAng papel ng Santa Rosa sa Himagsikang Pilipino\n\t\tAng Santa Rosa ay isang mahalagang lugar sa Himagsikang Pilipino laban sa mga Espanyol. Noong 1898, lumagda ang Santa Rosa sa Act of Independence, na nagproklama ng Kalayaan ng Pilipinas mula sa Espanya.\n\n\t\tWorld War II\n\t\tPananakop ng Hapon: Noong World War II, pansamantalang sinakop ng mga Hapon ang Santa Rosa.",
        "CALABARZON MEANING OF MEANS": "  Ang Calabarzon ay ang pangalan ng isang administratibong rehiyon sa Pilipinas na binubuo ng limang lalawigan: Cavite, Laguna, Batangas, Rizal, at Quezon. Ang pangalan ay isang acronym ng unang titik ng bawat lalawigan.",
        "WHY IS IT CALLED CALABARZON": "  Ang rehiyon ay nilikha upang pagsamahin ang panlipunan at pang-ekonomiyang pag-unlad ng limang lalawigan.\n\t\tKilala rin ito bilang Region IV-A.",
        "IN WHAT ASPECT IS CALABARZON KNOWN": "  Ang Calabarzon ay kilala bilang industrial powerhouse ng Pilipinas.\n\t\tTahanan ito ng marami sa mga pinakamataong lalawigan ng bansa.\n\t\tIto ang lugar ng kapanganakan ng kalayaan ng Pilipinas mula sa Espanya noong 1898.\n\t\tIto ang lugar ng kapanganakan ng mga pambansang bayani tulad ni Jose Rizal.\n\t\tTahanan ito ng maraming tradisyong pangkultura, kabilang ang pag-ukit ng kahoy at taka (papier-mâché).",
        "WHAT IS THE RANKING POSITION OF SANTA ROSA, LAGUNA WHEN IT COMES TO ITS RANKING AMONG NEARBY CITIES IN THE ENTIRE COUNTRY": "  Ang Santa Rosa, Laguna ay isang prominenteng lungsod sa Pilipinas, at itinuturing na pinakamayamang lungsod sa Luzon sa labas ng Metro Manila. Isa rin ito sa pinakamabilis na lumalagong ekonomiya sa bansa.\n\n\t\tRanking:\n\t\tNoong 2019, niranggo ang Santa Rosa bilang pangatlo sa bansa para sa kahusayan nito sa pagkolekta ng lokal na kita.\nNoong 2022, nagkaroon ang Santa Rosa ng pinakamataas na kita sa anumang lokal na pamahalaan (LGU) sa Laguna.",
        "WHERE WAS DR. JOSE RIZAL BORN": "  Calamba, Laguna",
        "WHEN WAS DR. JOSE RIZAL BORN": "  Hunyo 19, 1861",
        "WHAT IS THE FULL NAME OF DR. JOSE RIZAL": "  Jose Protacio Rizal Mercado y Alonso Realonda",
        "WHO ARE THE PARENTS OF DR. JOSE RIZAL": " Francisco Mercado at Teodora Alonso Realonda",
        "WHO IS THE FATHER OF DR. JOSE RIZAL": "  Francisco Mercado ",
        "WHO IS THE MOTHER OF DR. JOSE RIZAL": "  Teodora Alonso Realonda",
        #Attractions/ tourist destination in Santa Rosa
        "NATURE ATTRACTION IN LAGUNA": "  Pagsanjan Falls\n\t\tHulugan Falls\n\t\tHidden Valley Falls\n\t\tTaytay Falls\n\t\tLake Pandin\n\t\tMount Makiling\n\t\tSampaloc Lake\n\t\tMt. Banahaw\n\t\tLake Yambo\n\t\tBangking Kahoy Valley\n\t\tLake Caliraya\n\t\tMakiling Botanic Gardens\n\t\tBukal Falls\n\t\tJapanese Garden\n\t\tDalitiwan River\n\t\tPanguil River Eco Park\n\t\tMount Kalisungan\n\t\tCavinti Underground River and Caves Complex\n\t\tTayak Hill\n\t\tBunga Falls\n\t\tMt. Romelo\n\t\tBuntot Palos Falls\n\t\tKalayaan Twin Falls\n\t\tBuruwisan Falls\n\t\tPueblo El Salvador Nature’s Park and Picnic Grove\n\t\tMagdalena White Water River\n\t\tLake Palakpakin\n\t\tLake Calibato\n\t\tLake Bunot\n\t\tLake Muhikap\n\t\tHilabaan Island",
        "HISTORICAL PLACES IN SANTA ROSA, LAGUNA": "  Cuartel De Sto. Domingo\n\t\tSanta Rosa De Lima Parish Church\n\t\tMuseo De Santa Rosa\n\t\tCity Plaza\n\t\tSanta Rosa Arch",
        "LOCAL HERITAGE IN BIÑAN LAGUNA": "  Site of Historic Alberto Mansion\n\t\tSentrong Pangkultura ng Biñan (Old Municipal Building)\n\t\tSchool of Rizal Site and Museum\n\t\tSan Isidro Labrador Catholic Church\n\t\tVicente Ocampo House\n\t\tJose Rizal Monument\n\t\tLos Maduros Bandstand\n\t\tFrancisco Almeda House\n\t\tCasa Biñanese – Jacobo Gonzales House\n\t\tJacinto Francisco House\n\t\tFilomena Belizario Hernandez House\n\t\tAlberto Yaptinchay House\n\t\tPedro-Isidro Cariño Isidro House\n\t\tIluminado Valencia House\n\t\tBiñan Roman Catholic Cemetery Camposanto\n\t\tCasa Paroquial-Biñan Cursillo House\n\t\tGabaldon Building of Biñan Elementary School\n\t\tCapilla De San Jose\n\t\tOld Binyang PNR Station including its Office and Railway\n\t\tBiñan Municipal Cemetery\n\t\tFrancisco Baylon House\n\t\tFrancisco Guico House\n\t\tTeodora Velasco House\n\t\tLaureano Cariño House\n\t\tIsisdro Gonzalez House\n\t\tSoro-soro Prinza Dam\n\t\tHistoric Alberto Mansion",
        "BARANGAY BARANGAYS IN SANTA ROSA LAGUNA": "  May labing-walo (18) na barangay na matatagpuan sa Santa Rosa, Laguna. Ang mga sumusunod ay ang labing-walo (18) na barangay:\n\t\tAplaya\n\t\tBalibago\n\t\tCaingin\n\t\tDila\n\t\tDita\n\t\tDon Jose\n\t\tIbaba\n\t\tKanluran\n\t\tLabas\n\t\tMacabling\n\t\tMalitlit\n\t\tMalusak\n\t\tMarket Area\n\t\tPooc\n\t\tPulong Santa Cruz\n\t\tSanto Domingo\n\t\tSinalhan\n\t\tTagapo",
        "WHAT ARE THE ATTRACTIONS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN SANTA ROSA LAGUNA": "  Ang Santa Rosa City ay may maraming atraksyon na tiyak na magdudulot ng kasiyahan hindi lamang sa mga turista, kundi pati na rin sa mga mamamayan nito. Ito ang mga atraksyon na maiaalok ng Lion City of the South — Santa Rosa, Laguna:\n\n\t\tTheme Park\n\t\tEnchanted Kingdom\n\n\t\tShopping Centers\n\t\tSM City Santa Rosa\n\t\tRobinson's Mall\n\t\tAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\n\t\tWalterMart\n\t\tVictory Mall\n\t\tTarget Mall\n\t\tWest Borrough Town Center\n\t\tPaseo de Santa Rosa\n\t\tEton City Square\n\n\t\tFarms\n\t\tFun Farm at Sta. Elena\n\t\tHoly Carabao\n\n\t\tParks\n\t\tNuvali Park\n\t\tSanta Rosa's City Plaza\n\n\t\tResorts and Events Place\n\t\tDictado 1\n\t\tDictado 2\n\t\tDictado 3\n\t\tSouthpick Resort\n\t\tCalypso Resort Hotel\n\t\tCarvill Private Resort\n\t\tCesar's Cabin Private Resort\n\t\tCriselda Private Resort\n\t\tPopong's Bukid Private Resort\n\t\tOlive's Private Resort\n\t\tBayani Resort\n\t\tKyler and Kean Private Resort\n\t\tCasa Vallejo Events Place and Private Resort\n\t\tNMV Resort Farmview\n\t\tLas Asturias\n\t\tVilla Gilda Resort\n\t\tSherinai Events Place\n\t\tSouth Country Garden\n\t\tLouLyn's Resort\n\t\tPablo's Events Place\n\t\tMarigold's Farm Resort\n\t\tTAR's Family and  Private Resort\n\t\tBay View Resort\n\n\t\tHotels / Motels\n\t\tSeda Nuvali\n\t\tPaseo Premiere Hotel\n\t\tAsiatel Inn\n\t\tTechopark Hotel\n\t\tMicrotel\n\t\tEl Cielito Hotel\n\t\tCasa Emerita\n\t\tCandy Motel\n\t\tHotel Sogo\n\t\tMariposa Hotel\n\n\t\tOthers(Sta. Elena's Golf and Country Club)",
        "SHOPPING MALLS IN SANTA ROSA LAGUNA": "  Ito ang listahan ng mga Shopping Centers sa Santa Rosa:\n\t\tSM City Santa Rosa\n\t\tRobinson's Mall\n\t\tAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\n\t\tWalterMart\n\t\tVictory Mall\n\t\tTarget Mall\n\t\tWest Borrough Town Center\n\t\tPaseo de Santa Rosa\n\t\tEton City Square",
        "RESORTS AND EVENTS PLACE IN SANTA ROSA LAGUNA": "  Mayroong maraming pribado at pampublikong resorts at events place sa Santa Rosa, at kabilang dito ang:\n\t\tSouthpick Resort\n\t\tDictado 1\n\t\tDictado 2\n\t\tDictado 3\n\t\tCalypso Resort Hotel\n\t\tCarvill Private Resort\n\t\tCesar's Cabin Private Resort\n\t\tCriselda Private Resort\n\t\tPopong's Bukid Private Resort\n\t\tOlive's Private Resort\n\t\tKyler and Kean Private Resort\n\t\tCasa Vallejo Events Place and Private Resort\n\t\tNMV Resort Farmview\n\t\tLas Asturias\n\t\tVilla Gilda Resort\n\t\tBayani Resort\n\t\tSherinai Events Place\n\t\tSouth Country Garden\n\t\tLouLyn's Resort\n\t\tPablo's Events Place\n\t\tMarigold's Farm Resort\n\t\tTAR's Family and  Private Resort\n\t\tBay View Resort",
        "PARKS IN SANTA ROSA LAGUNA": "  Sa kasalukuyan, may dalawa (2) na available na parke sa Santa Rosa, at ito ang mga sumusunod:\n\t\tNuvali Park\n\t\tSanta Rosa's City Plaza",
        "THEME PARK IN SANTA ROSA": "  Ang Enchanted Kingdom, na kilala rin bilang EK, ay ang tanging theme park na matatagpuan sa Santa Rosa, kilala ito sa maraming masaya at nakakakilig na rides na maiaalok nito, pati na rin sa mga developed lot spaces na sinasakop nito.",
        # Lodging Area in Santa Rosa
        "LODGING AREA HOTEL MOTEL HOTELS MOTELS IN SANTA ROSA": "  Ito ang ilan sa mga Hotels, o Motels, na sikat sa lungsod:\n\t\tSeda Nuvali\n\t\tPaseo Premiere Hotel\n\t\tAsiatel Inn\n\t\tTechopark Hotel\n\t\tMicrotel\n\t\tEl Cielito Hotel\n\t\tCasa Emerita\n\t\tCandy Motel\n\t\tHotel Sogo\n\t\tMariposa Hotel",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY POOC": "  Sa kabuuan, may limang (5) resorts na matatagpuan sa Barangay Pooc, at ito ang mga sumusunod:\n\t\tCarvill Private Resort\n\t\tCriselda Private Resort\n\t\tPopong's Bukid Private Resort\n\t\tOlive's Private Resort\n\t\tKyler and Kean Private Resort\n\n\t\tAng mga nabanggit na resorts ay matatagpuan sa Caramay Compound, La Concordia, Barangay Pooc, City of Santa Rosa, Laguna.",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY MARKET AREA": "  Ang Barangay Market Area ay may limang (5) resorts na maiaalok, at ito ay:\n\t\tSouthpick Resort\n\t\tPablo's Events Place\n\t\tDictado 1\n\t\tDictado 2\n\t\tDictado 3",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY SINALHAN": "  Sa kasalukuyan, walang resorts na matatagpuan sa Barangay Sinalhan",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY TAGAPO": "  Ito ang mga resort na maiaalok ng Barangay Tagapo:\n\t\tLouLyn's Resort\n\t\tTAR's Family and Private Resort\n\t\tNMV Resort\n\t\tSherinai Events Place\n\t\tMarigold's Farm Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY IBABA": "  Ito ang tanging resort na maiaalok ng Barangay Ibaba:\n\t\tCasa Vallejo Events Place and Private Resort",
        "RESORTS THAT CAN FOUND LOCATE LOCATED LOCATION OF IN BARANGAY CAINGIN": "  Ito ang tanging resorts na maiaalok ng Barangay Caingin:\n\t\tVilla Gilda Resort\n\t\tBayani Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY DITA": "  Ito ang tanging resort na matatagpuan sa Barangay Dita:\n\t\tSouth Country Garden",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED IN BARANGAY MACABLING": "  Ang tanging resort na matatagpuan sa Barangay Macabling ay:  Calypso Resort ",
        # Emergency Services in Santa Rosa
        "EMERGENCY CLINIC CLINICS MEDICAL AID HOSPITALS HOSPITAL IN SANTA ROSA": "  St. James Hospital\n\t\tSanta Rosa Community Hospital\n\t\tNew Sinai MD Hospital\n\t\tThe Medical City South Luzon\n\t\tUnihealth Santa Rosa Hospital and Medical Center\n\t\tMarian Hospital\n\t\tCity Medic Emergency Hospital\n\t\tBalibago Polyclinic and Hospital, Inc.\n\t\tSanta Rosa Hospital and Medical Center\n\t\tHealthway QualiMed Hospital Santa Rosa\n\t\tThe Medical City, South Luzon",
        "FIND AREA LOCATED LOCATION OF ST. JAMES HOSPITAL": "Ang lokasyon ng St. James Hospital ay Brgy. Dita, JP. Rizal Street, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF ST. JAMES HOSPITAL": "  Ito ang mga accessible na contact/ hotline numbers, at email address ng St. James Hospital: \n\t\tLine Numbers: 0933-825-6214\n\t\t\t      (02)8584-4533\n\t\t\t      (049)534-1254\n\t\t\t      (049)502-0058",
        "FIND AREA LOCATED LOCATION OF NEW SINAI MDI HOSPITAL": "Ang lokasyon ng New Sinai MDI Hospital ay National Highway, Brgy Tagapo, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF NEW SINAI MDI HOSPITAL": "  Ito ang mga accessible na contact/ hotline number ng New Sinai MDI Hospital\n\t\tLine Number: 0917-180-6534",
        "FIND AREA LOCATED LOCATION OF SANTA ROSA COMMUNITY HOSPITAL": "Ang lokasyon ng Santa Rosa Community Hospital ay LM Subdivision, Brgy. Market Area, Cattleya St. Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF SANTA ROSA COMMUNITY HOSPITAL": "  Ito ang mga accessible na contact/ hotline number ng Santa Rosa Community Hospital\n\t\tLine Number: 0950-666-8525",
        "FIND AREA LOCATED LOCATION OF MEDICAL CITY SOUTH LUZON": "Ang lokasyon ng Medical City South Luzon ay Greenfield City, Brgy. Don Jose, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF MEDICAL CITY SOUTH LUZON": "  Ito ang mga accessible na contact/ hotline number ng Medical City of South Luzon\n\t\tLine Number: (049)303-3000\n\t\t\t      (639)20-981-4454\n\t\tEmail: tmcsl.customercare@themedicalcity.com",
        "FIND AREA LOCATED LOCATION OF UNIHEALTH-SANTA ROSA": "Ang lokasyon ng Unihealth-Santa Rosa ay RSBS Blvd., San Lorenzo South, Brgy. Balibago, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF UNIHEALTH-SANTA ROSA": "  Ito ang mga accessible na contact/ hotline number ng Unihealth-Santa Rosa\n\t\tLine Number: (+63)999-880-7519\n\t\t\t      (+63)917-825-2335\n\t\tEmail: starosamed08@gmail.com",
        "FIND AREA LOCATED LOCATION OF MARIAN HOSPITAL": "Ang lokasyon ng Marian Hospital ay Rizal Blvd., Brgy. Tagapo, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF MARIAN HOSPITAL": "  Ito ang mga accessible na contact/ hotline number ng Marian Hospital\n\t\tLine Number: (02)8584-4483",
        "FIND AREA LOCATED LOCATION OF CITY MEDIC EMERGENCY HOSPITAL": "Ang lokasyon ng City Medic Emergency Hospital ay Rizal Blvd., Brgy. Tagapo, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF CITY MEDIC EMERGENCY HOSPITAL": "  Ito ang mga accessible na contact/ hotline number ng City Medic Emergency Hospital:\n\t\tLine Number: 09671134164",
        "FIND AREA LOCATED LOCATION OF BALIBAGO POLYCLINIC AND HOSPITAL INC.": "Ang lokasyon ng Balibago Polyclinic and Hospital Inc ay Rizal Blvd., Brgy. Balibago, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF BALIBAGO POLYCLINIC AND HOSPITAL INC.": "  Ito ang mga accessible na contact/ hotline number ng Balibago Polyclinic Hospital:\n\t\tLine Number: 09106703156",
        "FIND AREA LOCATED LOCATION OF SANTA ROSA MEDICAL AND HOSPITAL CENTER": "Ang lokasyon ng Santa Rosa Medical and Hospital Center ay Brgy. Balibago, San Lorenzon Rd, Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF SANTA ROSA MEDICAL AND HOSPITAL CENTER": "  Ito ang mga accessible na contact/ hotline number ng Santa Rosa Medical and Hospital center:\n\t\tLine Number: 09106703156",
        "FIND AREA LOCATED LOCATION OF HEALTHWAY QUALIMED HOSPITAL SANTA ROSA": "Ang lokasyon ng Healthway QualiMed Hospital Santa Rosa ay Brgy. Sto. Domingo, Nuvali North, West Nature Ave., Lungsod ng Santa Rosa Laguna",
        "CALL PHONE NUMBER CONTACT INFORMATION INFORMATIONS OF HEALTHWAY QUALIMED HOSPITAL SANTA ROSA": "  Ito ang mga accessible na contact/ hotline number ng Healthway Qualimed Hospital Santa Rosa:\n\t\tLine Number: 09174662273\n\t\t\t     (02)7777-2273",
        #Transportation in Santa Rosa
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBBL Bus Terminal\n\t\tBalibago - Sta. Cruz Van Terminal\n\t\tBalibago Transport Terminal - Sta. Rosa\n\t\tAlabang Express Jeepney Terminal\n\t\tShuttle Service Terminal\n\t\tVan terminal\n\t\tJAM Bus Terminal\n\t\tPaseo De StaRosa\n\t\tUBE Express - Robinsons Sta. Rosa\n\t\tJam Liner Bus Stop\n\t\tTodap Terminal\n\t\tBBPL Transport Terminal\n\t\tBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\n\t\tPaseo de Sta Rosa - Calamba Jeepney Terminal\n\t\tJam Transit Inc. Terminal - Penta\n\t\tTricycle terminal\nHM Terminal-Target\n\t\tNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A JEEPNEY TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tBalibago Transport Terminal - Sta. Rosa\n\t\tAlabang Express Jeepney Terminal\n\t\tPaseo De StaRosa\n\t\tBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\n\t\tPaseo de Sta Rosa - Calamba Jeepney Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A BUS TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBBL Bus Terminal\n\t\tShuttle Service Terminal\n\t\tJAM Bus Terminal\n\t\tUBE Express - Robinsons Sta. Rosa\n\t\tJam Liner Bus Stop\n\t\tBBPL Transport Terminal\n\t\tJam Transit Inc. Terminal - Penta\n\t\tHM Terminal-Target\n\t\tNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A VAN TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBalibago - Sta. Cruz Van Terminal\n\t\tBalibago Transport Terminal - Sta. Rosa\n\t\tShuttle Service Terminal\n\t\tVan terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TRICYCLE TERMINAL": "  Paseo De StaRosa\n\t\tTodap Terminal\n\t\tTricycle terminal"
    }
    return data

def reply(sentence: str, data: dict)->None:
    compare: dict = {key: 0 for key in data.keys()} # Will start at 0 and For every key/question in data
        
    input_words = set(sentence.split()) # Converted to set to efficiently handles matching, and split keys in the data
                                        # input_words is a set of word per word from self.sentence/from the input of the user
    for key, responses in data.items():
        key_words = set(key.split()) # key_word is a set of word per word from each key in data
        compare[key] = len(input_words & key_words)  # This will match how many words match in input_words & key_words using &/ intersection operator

    highest_value = max(compare.values())

    if highest_value == 0: # No match, highest matches does not have any element and is equal to 0
        print("AskSantaRosa: I'm sorry, I don't understand that.")
        return

    matching_keys = [k for k, v in compare.items() if v == highest_value] # Will look for the keys in compare that will match the value of highest_matches
    if len(matching_keys) == 1: # If it is only 1 match
        print(f"AskSantaRosa: {data[matching_keys[0]]}")
    else:
        # If their is a tie, the first match will be picked
        print(f"AskSantaRosa: {data[matching_keys[0]]}")

def main()->None:
    language = main_introduction()
    while True:
        if language == "FILIPINO" :
            sentence = user_input_fil()
            data = fil_data()
        else:
            sentence = user_input_EN()
            data = en_data()
        if sentence == 'EXIT':
            break
        reply(sentence.upper(), data)

if __name__ == '__main__':
    main()