from deep_translator import GoogleTranslator

def main_introduction()->str:
    print("City of Santa Rosa Tourist HelpDesk Chatbot")
    language: str = input("chatbot name: Pumili ng wika na nais | Choose your preferred language: Filipino or English: ").upper()
    functions: dict = {"FILIPINO": fil_introuction, "ENGLISH": en_introduction}
    while language not in functions:
        print("Ang wikang pinili ay wala sa aming system | The language you pick is not available in our system")
        language = input("Ilagay muli ang nais na wika | Enter again your preferred language: ").upper()

    functions[language]()  # Call the corresponding introduction
    return language  # Return the selected language
        
def en_introduction()->None:
    print("AskSantaRosa: Hi my name is AskSantaRosa")
    print("AskSantaRosa: You can ask me anything about the city of Santa Rosa")
    print("AskSantaRosa: Enter 'exit' to exit the program")

def fil_introuction()->None:
    print("AskSantaRosa: Kamusta ang pangalan ko ay AskSantaRosa")
    print("AskSantaRosa: Pwede mo kong tanungin ng tungkol sa bayan ng Santa Rosa")
    print("AskSantaRosa: I-type lamang ang 'exit' upang matapos ang program")

def user_input_EN()->str:
    question: str = input("user: ").upper()
    if question == 'EXIT':
        return 'EXIT'
    return (question).upper()

def user_input_fil()->str:
    question: str = input("user: ").upper()
    if question == 'EXIT':
        return 'EXIT'
    while True:
        try:
            translation = GoogleTranslator(source='tl', target='en').translate(question)
            translation.upper().strip()
            return translation
        except Exception as e:
            print(f"Nagkaroon ng error sa pag-translate: {e}")
            question = input("Ilagay muli ang tanong: ").upper()

def en_data()->dict:
    data = {
        "HOW ARE YOU": "Mabuti, Salamat sa pagtanong!",
        "INDUSTRIAL ESTATE WITHIN SANTA ROSA LAGUNA": "  Laguna Technopark Inc.\n\t\tGreenfield Automotive Park.\n\t\tToyota Special Economic Zone.\n\t\tLakeside Evozone Nuvali.\n\t\tDaystar Santa Rosa Industrial Park.\n\t\tSanta Rosa Commercial Complex.\n\t\tnMeridian Industrial Complex.",
        "SCHOOLS WITHIN SANTA ROSA LAGUNA": "\nColegio de Santa Rosa de Lima\nThe Canossa School, Inc. City of Santa Rosa, Laguna\nQueen Anne School of Sta. Rosa\nBlessed Christian School de Sta. Rosa\nHoly Rosary College of Santa Rosa, Laguna, Inc.\nMaranatha Living Hope Academy\nDila Elementary School\nFaithful Grace Christian School\nSanta Rosa Science and Technology High School\nDominican College of Santa Rosa\nBalibago Integrated High School\nSaint Ruiz Montessori School\nGreen Fields Integrated School of Laguna, Inc.\nOur Lady of Fatima University Sta. Rosa, Laguna\nSts. Paul & Mark School Inc\nMarie Margarette School\nSouthville 4 National High School\nJesus The Exalted Name School\nSanta Rosa Elementary School Central I HACIENDA DOMINICANO\nPolytechnic University of Philippines",
        "SIKHAYAN FESTIVAL": "Sikhayan Festival is a yearly cultural celebration in Santa Rosa City, Laguna, Philippines. It's a celebration of the city's founding and a way to honor the community's traditions and pride.",
        "SIKHAYAN MEANS MEANING SIGNIFY": "Sikhayan is a Filipino word that means \"diligence\" and \"livelihood\". It is also the name of an annual festival in Santa Rosa, Laguna, Philippines. The festival celebrates the people of Santa Rosa, their entrepreneurial spirit, and their resilience.\nSikhayan Festival comes from sikap (hardwork) and kabuhayan (livelihood).",
        "HISTORY OF SIKHAYAN FESTIVAL": "It was launched in 2000 by Mayor Leon Arcillas to celebrate the historic beginning of Santa Rosa City every year and a way to give recognition to it people, their resilience, and their entrepreneurial spirit that drive the city's continuous economic prosperity and growth.",
        "SANTA ROSA LAGUNA IS KNOWN FOR": "Santa Rosa, Laguna is known for its industrial estates, theme park, and the Santa Rosa Arch.\nOne of the two largest municipalities in Laguna, Santa Rosa City, also known as the Lion City of the South, is located west of Laguna de Bay.\nSta Rosa was mainly known for the Coca-Cola and Toyota manufacturing plants in its industrial estates. More recently it has also become famous for being the site of Enchanted Kingdom, a local theme park, as well as several housing developments. Santa Rosa is also the exit travellers take along the South Luzon Expressway to go to Tagaytay and Taal Volcano. This city contains the 3rd largest complex in Laguna, Paseo de Santa Rosa.",
        "SANTA ROSA CITY CALLED THE LION CITY OF THE SOUTH": "\n\tIt is one of the Philippines’ fastest-growing economies. On March 10, 2004, the Philippine Congress approved Republic Act No. 9264, which made the city of Santa Rosa the first-class municipality from a fourth-class municipality. On July 10, 2004, Santa Rosa was proclaimed the country’s 101st city.\n\n\tThe city of Santa Rosa has made a name for itself in just three short years after it was transformed into a city and is now known for several economic triumphs. To put the City in the Billionaire’s Club among Philippine local government entities, the City’s 2007 income surpassed the one billion mark, from less than Php 600 million in 2003. Moreover, the flood of foreign and local investors interested in Santa Rosa has helped it treble its annual income during the last decade. Thus, making Santa Rosa the \“Lion City of the South.\”",
        "WHEN DID SANTA ROSA LAGUNA BECOME A CITY": "\n\tIt is one of the Philippines’ fastest-growing economies. On March 10, 2004, the Philippine Congress approved Republic Act No. 9264, which made the city of Santa Rosa the first-class municipality from a fourth-class municipality. On July 10, 2004, Santa Rosa was proclaimed the country’s 101st city.\n\n\tThe city of Santa Rosa has made a name for itself in just three short years after it was transformed into a city and is now known for several economic triumphs. To put the City in the Billionaire’s Club among Philippine local government entities, the City’s 2007 income surpassed the one billion mark, from less than Php 600 million in 2003. Moreover, the flood of foreign and local investors interested in Santa Rosa has helped it treble its annual income during the last decade. Thus, making Santa Rosa the \“Lion City of the South.\”",
        "TOTAL POPULATION OF SANTA ROSA LAGUNA": "Its population as determined by the 2020 Census was 414,812. This represented 12.26% of the total population of Laguna province, or 2.56% of the overall population of the CALABARZON region.",
        "MEANING MEAN SIGNIFIES THE PLAZA IN SANTA ROSA LAGUNA": "\nThe plaza in Santa Rosa, Laguna, Philippines, symbolizes the city's history, culture, and heritage. The plaza features the Jose Rizal monument, which represents the city's martyrs and their fight for freedom.\n\nWhat does the square symbolize:\nHistory: The square was the place of execution of local guerrillas.\nCulture: The square is part of the Spanish-era city center of the city, which is being converted into a \"heritage square\".\nHeritage: The square is home to heritage houses and government offices.\nFreedom: The monument of Jose Rizal symbolizes the martyrs of the city and their fight for freedom.",
        "JOSE RIZAL MONUMENT MEANING SYMBOLIZE IN THE PLAZA OF SANTA ROSA LAGUNA": "\nMartyrdom: The monument symbolizes the sacrifice of life for freedom.\nWisdom: The monument symbolizes the wisdom and bravery of the people of Santa Rosa.\nLight over darkness: The monument symbolizes the idea that light will always triumph over darkness.",
        "WHO ESTABLISHED THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINE SANTA ROSA CAMPUS": "\nThe Polytechnic University of the Philippines (PUP) Santa Rosa Campus was established by the Senate and House of Representatives of the Philippines through Republic Act No. 11784. This act is also known as the PUP-Santa Rosa Campus Act.",
        "WHO REQUESTED TO BUILD A BRANCH CAMPUS OF THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINES IN SANTA ROSA LAGUNA": "\nThe late mayor of Santa Rosa, Laguna, Hon. Leon C. Arcillas, requested the construction of the Polytechnic University of the Philippines (PUP) Santa Rosa Campus. The campus opened in 2003 and is considered a legacy of Arcillas's efforts to provide quality education to the residents of Santa Rosa and nearby towns.\nThe Polytechnic University of the Philippines was originally established as the Manila Business School in 1904. In 1978, the Philippine College of Commerce (PCC) was renamed PUP through Presidential Decree (PD) 1341.",
        "WHAT IS THE CHURCH'S NAME LOCATED BEHIND THE PLAZA OF SANTA ROSA LAGUNA": "\nSanta Rosa de Lima Parish Church",
        "WHEN WAS THE SANTA ROSA DE LIMA PARISH CHURCH BUILT": "\nThe Santa Rosa de Lima Parish Church in Santa Rosa, Laguna, Philippines was established in 1792. The church was built by Spanish Catholic priest Francisco Favie.",
        "THE HISTORY OF THE SANTA ROSA DE LIMA PARISH CHURCH": "\nThe Santa Rosa de Lima Parish Church in Santa Rosa, Laguna, Philippines was built in 1792 by Spanish Catholic priest Francisco Favie. The church was named after Saint Rose of Lima, the patron saint of the Philippines, America, and the East Indies.\n\nConstruction:\nThe church and convent were built within 12 years\nThe present church building was constructed in 1796 by Spanish friars with help from Chinese laborers\nThe church was blessed on August 4, 1812\nThe first Mass was held on August 30, 1812\n\nHistory:\nBefore the church was built, the area was called \"Bucol\"\nThe residents changed the name of the area to \"Santa Rosa\" in honor of the patron saint\nThe original structure still stands and is now known as Museo de Santa Rosa\n\nSaint Rose of Lima\nSaint Rose of Lima was born Isabel Flores de Oliva in Lima, Peru in 1586\nShe was known for helping the sick and hungry in her community\nShe was given the name Rose by a housemaid who said she was \"as lovely as a rose\"",
        "HISTORICAL TIMELINE OF SANTA ROSA LAGUNA": "\nThe historical timeline of Santa Rosa, Laguna, Philippines includes the Spanish colonization, the Philippine Revolution, and the post-war era.\n1571: Spanish Conquistador Juan de Salcedo discovers Biñan and annexes it to Tabuco\n1688: Barrio Bukol separates from Cabuyao\n1792: Barrio Bukol becomes the municipality of Santa Rosa\n1812: The Saint Rose of Lima Parish Church is blessed\n1859–1860: The Santa Rosa Arch is built to replace a Spanish guard tower\n1898: Santa Rosa plays a key role in the Philippine Revolution against Spain and signs the Act of Independence\n1945: Santa Rosa is liberated from Japanese occupation during World War II\n1970s: The economy of Santa Rosa is based on agriculture and family-owned businesses\n1980s: Industrialization and foreign investment transform Santa Rosa's economy and society\n2004: Santa Rosa becomes a city",
        "HISTORICAL HISTORY BACKGROUND OF SANTA ROSA LAGUNA": "\nSanta Rosa, Laguna, Philippines has a rich history that includes its role in the Philippine Revolution, its time under Japanese occupation, and its development from an agricultural town to a modern city.\n\nEarly history\nBarrio Bukol\nIn 1688, Barrio Bukol separated from Cabuyao and became part of Biñan.\n\nSaint Rose of Lima Parish Church\nIn 1792, the Spanish Catholic priest Francisco Favie built the Saint Rose of Lima Parish Church.\n\nMunicipality of Santa Rosa\nIn 1792, Barrio Bukol became its own municipality and was named after Saint Rose of Lima.\n\nSanta Rosa's role in the Philippine Revolution\nSanta Rosa was a key site in the Philippine Revolution against the Spanish. In 1898, Santa Rosa signed the Act of Independence, which proclaimed Philippine Independence from Spain.\n\nWorld War II\nJapanese occupation: During World War II, the Japanese briefly occupied Santa Rosa.",
        "WHAT CALABARZON MEANS MEANING OF": "Calabarzon is the name of an administrative region in the Philippines that's made up of five provinces: Cavite, Laguna, Batangas, Rizal, and Quezon. The name is an acronym of the first letter of each province.",
        "WHY IS IT CALLED CALABARZON": "The region was created to integrate the social and economic development of the five provinces.\nIt's also known as Region IV-A.",
        "IN WHAT ASPECT IS CALABARZON KNOWN": "Calabarzon is known as the industrial powerhouse of the Philippines.\nIt's home to many of the country's most densely populated provinces.\nIt's the birthplace of Philippine independence from Spain in 1898.\nIt's the birthplace of national heroes like Jose Rizal.\nIt's home to many cultural traditions, including wood carving and taka (papier-mâché).",
        "WHAT IS THE RANKING POSITION OF SANTA ROSA LAGUNA WHEN IT COMES TO ITS RANKING AMONG NEARBY CITIES IN THE ENTIRE COUNTRY": "\nSanta Rosa, Laguna is a prominent city in the Philippines, and is considered the richest city in Luzon outside of Metro Manila. It is also one of the fastest-growing economies in the country.\n\nRanking:\nIn 2019, Santa Rosa was ranked third in the country for its collection efficiency of locally sourced revenues.\nIn 2022, Santa Rosa had the highest revenue of any local government unit (LGU) in Laguna.",
        "WHERE WAS DR. JOSE RIZAL BORN": "Calamba, Laguna",
        "WHEN WAS DR. JOSE RIZAL BORN": "June 19, 1861",
        "WHAT IS THE FULL NAME OF DR. JOSE RIZAL": "Jose Protacio Rizal Mercado y Alonso Realonda",
        "WHO ARE THE PARENTS OF DR. JOSE RIZAL": "Francisco Mercado and Teodora Alonso Realonda",
        "WHO IS THE FATHER OF DR. JOSE RIZAL": "Francisco Mercado ",
        "WHO IS THE MOTHER OF DR. JOSE RIZAL": "Teodora Alonso Realonda",
        "NATURE ATTRACTION IN LAGUNA": "Pagsanjan Falls\n\tHulugan Falls\n\tHidden Valley Falls\n\tTaytay Falls\n\tLake Pandin\n\tMount Makiling\n\tSampaloc Lake\n\tMt. Banahaw\nLake Yambo\nBangking Kahoy Valley\nLake Caliraya\nMakiling Botanic Gardens\nBukal Falls\nJapanese Garden\nDalitiwan River\nPanguil River Eco Park\nMount Kalisungan\nCavinti Underground River and Caves Complex\nTayak Hill\nBunga Falls\nMt. Romelo\nBuntot Palos Falls\nKalayaan Twin Falls\nBuruwisan Falls\nPueblo El Salvador Nature’s Park and Picnic Grove\nMagdalena White Water River\nLake Palakpakin\nLake Calibato\nLake Bunot\nLake Muhikap\nHilabaan Island",
        "HISTORICAL PLACES IN SANTA ROSA LAGUNA": "\nCuartel De Sto. Domingo\nSanta Rosa De Lima Parish Church\nMuseo De Santa Rosa\nCity Plaza\nSanta Rosa Arch",
        "LOCAL HERITAGE IN BIÑAN LAGUNA": "\nSite of Historic Alberto Mansion\nSentrong Pangkultura ng Biñan (Old Municipal Building)\nSchool of Rizal Site and Museum\nSan Isidro Labrador Catholic Church\nVicente Ocampo House\nJose Rizal Monument\nLos Maduros Bandstand\nFrancisco Almeda House\nCasa Biñanese – Jacobo Gonzales House\nJacinto Francisco House\nFilomena Belizario Hernandez House\nAlberto Yaptinchay House\nPedro-Isidro Cariño Isidro House\nIluminado Valencia House\nBiñan Roman Catholic Cemetery Camposanto\nCasa Paroquial-Biñan Cursillo House\nGabaldon Building of Biñan Elementary School\nCapilla De San Jose\nOld Binyang PNR Station including its Office and Railway\nBiñan Municipal Cemetery\nFrancisco Baylon House\nFrancisco Guico House\nTeodora Velasco House\nLaureano Cariño House\nIsisdro Gonzalez House\nSoro-soro Prinza Dam\nHistoric Alberto Mansion",
        "BARANGAYS IN SANTA ROSA LAGUNA": "\nThere are eighteen (18) baranggays that can be found in Santa Rosa, Laguna. The following are the eighteen (18) baranggays:\nAplaya\nBalibago\nCaingin\nDila\nDita\nDon Jose\nIbaba\nKanluran\nLabas\nMacabling\nMalitlit\nMalusak\nMarket Area\nPooc\nPulong Santa Cruz\nSanto Domingo\nSinalhan\nTagapo",
        "WHAT ARE THE ATTRACTIONS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN SANTA ROSA, LAGUNA": "\nSanta Rosa City have many attractions that can surely bring happiness not just to tourists, but also to its citizens. These are the attractions, that the Lion City of the South — Santa Rosa, Laguna, can offer:\n\nTheme Park\nEnchanted Kingdom\n\nShopping Centers\nSM City Santa Rosa\nRobinson's Mall\nAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\nWalterMart\nVictory Mall\nTarget Mall\nWest Borrough Town Center\nPaseo de Santa Rosa\nEton City Square\n\nFarms\nFun Farm at Sta. Elena\nHoly Carabao\n\nParks\nNuvali Park\nSanta Rosa's City Plaza\n\nResorts and Events Place\nDictado 1\nDictado 2\nDictado 3\nSouthpick Resort\nCalypso Resort Hotel\nCarvill Private Resort\nCesar's Cabin Private Resort\nCriselda Private Resort\nPopong's Bukid Private Resort\nOlive's Private Resort\nBayani Resort\nKyler and Kean Private Resort\nCasa Vallejo Events Place and Private Resort\nNMV Resort Farmview\nLas Asturias\nVilla Gilda Resort\nSherinai Events Place\nSouth Country Garden\nLouLyn's Resort\nPablo's Events Place\nMarigold's Farm Resort\nTAR's Family and  Private Resort\nBay View Resort\n\nHotels / Motels\nSeda Nuvali\nPaseo Premiere Hotel\nAsiatel Inn\nTechopark Hotel\nMicrotel\nEl Cielito Hotel\nCasa Emerita\nCandy Motel\nHotel Sogo\nMariposa Hotel\n\nOthers(Sta. Elena's Golf and Country Club)",
        "SHOPPING MALLS IN SANTA ROSA LAGUNA": "\nThese are the list of Santa Rosa's thriving Shopping Centers:\nSM City Santa Rosa\nRobinson's Mall\nAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\nWalterMart\nVictory Mall\nTarget Mall\nWest Borrough Town Center\nPaseo de Santa Rosa\nEton City Square",
        "RESORTS AND EVENTS PLACE IN SANTA ROSA LAGUNA": "\nThere are numerous private, and public resorts, and events place in Santa Rosa, and these includes:\nSouthpick Resort\nDictado 1\nDictado 2\nDictado 3\nCalypso Resort Hotel\nCarvill Private Resort\nCesar's Cabin Private Resort\nCriselda Private Resort\nPopong's Bukid Private Resort\nOlive's Private Resort\nKyler and Kean Private Resort\nCasa Vallejo Events Place and Private Resort\nNMV Resort Farmview\nLas Asturias\nVilla Gilda Resort\nBayani Resort\nSherinai Events Place\nSouth Country Garden\nLouLyn's Resort\nPablo's Events Place\nMarigold's Farm Resort\nTAR's Family and  Private Resort\nBay View Resort",
        "PARKS IN SANTA ROSA LAGUNA": "\nCurrently, there are two (2) available parks in Santa Rosa, and these are what follows:\nNuvali Park\nSanta Rosa's City Plaza",
        "THEME PARK IN SANTA ROSA": "\nEnchanted Kingdom, also known as EK, is the only theme park that can be found in Santa Rosa, it is known for numerous fun and nerve-wracking rides it can offer, as well as the developed lot spaces it occupies.",
        "HOTELS OR MOTELS IN SANTA ROSA": "\nThese are some of the Hotels, or Motels, that are famous, in the City:\nSeda Nuvali\nPaseo Premiere Hotel\nAsiatel Inn\nTechopark Hotel\nMicrotel\nEl Cielito Hotel\nCasa Emerita\nCandy Motel\nHotel Sogo\nMariposa Hotel",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY POOC": "\nIn total, there are five (5) resorts located in Barangay Pooc, and these are what follows:\nCarvill Private Resort\nCriselda Private Resort\nPopong's Bukid Private Resort\nOlive's Private Resort\nKyler and Kean Private Resort\n\nThe mentioned resorts, are all located in  Caramay Compound, La Concordia, Barangay Pooc, City of Santa Rosa, Laguna.",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY MARKET AREA": "\nBarangay Market Area have five(5) resorts can offer, and these are:\nSouthpick Resort\nPablo's Events Place\nDictado 1\nDictado 2\nDictado 3",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY SINALHAN": "\nCurrently, There are no resorts that can be found in Barangay Sinalhan",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY TAGAPO": "\nThese are the resort Barangay Tagapo can offer:\nLouLyn's Resort\nTAR's Family and Private Resort\nNMV Resort\nSherinai Events Place\nMarigold's Farm Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY IBABA": "\nThese is the only resort Barangay Ibaba can offer:\nCasa Vallejo Events Place and Private Resort",
        "RESORTS THAT CAN FOUND LOCATE LOCATED LOCATION OF IN BARANGAY CAINGIN": "\nThese are the only resorts Barangay Caingin can offer:\nVilla Gilda Resort\nBayani Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY DITA": "\nThese is the only resort that can be found in Barangay Dita:\nSouth Country Garden",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED IN BARANGAY MACABLING": "\nThe only resort that can be found in Barangay Macabling is:\nCalypso Resort ",
        "EMERGENCY SERVICES": "\nSt. James Hospital\nSanta Rosa Community Hospital\nNew Sinai MD Hospital\nThe Medical City South Luzon\nUnihealth Santa Rosa Hospital and Medical Center\nMarian Hospital\nCity Medic Emergency Hospital\nBalibago Polyclinic and Hospital, Inc.\nSanta Rosa Hospital and Medical Center\nHealthway QualiMed Hospital Santa Rosa\nThe Medical City, South Luzon",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TERMINAL": "\nSta. Rosa Complex Central Terminal\nSanta Rosa Integrated Terminal (SRIT)\nBBL Bus Terminal\nBalibago - Sta. Cruz Van Terminal\nBalibago Transport Terminal - Sta. Rosa\nAlabang Express Jeepney Terminal\nShuttle Service Terminal\nVan terminal\nJAM Bus Terminal\nPaseo De StaRosa\nUBE Express - Robinsons Sta. Rosa\nJam Liner Bus Stop\nTodap Terminal\nBBPL Transport Terminal\nBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\nPaseo de Sta Rosa - Calamba Jeepney Terminal\nJam Transit Inc. Terminal - Penta\nTricycle terminal\nHM Terminal-Target\nNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A JEEPNEY TERMINAL": "\nSta. Rosa Complex Central Terminal\nBalibago Transport Terminal - Sta. Rosa\nAlabang Express Jeepney Terminal\nPaseo De StaRosa\nBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\nPaseo de Sta Rosa - Calamba Jeepney Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A BUS TERMINAL": "\nSta. Rosa Complex Central Terminal\nSanta Rosa Integrated Terminal (SRIT)\nBBL Bus Terminal\nShuttle Service Terminal\nJAM Bus Terminal\nUBE Express - Robinsons Sta. Rosa\nJam Liner Bus Stop\nBBPL Transport Terminal\nJam Transit Inc. Terminal - Penta\nHM Terminal-Target\nNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A VAN TERMINAL": "Sta. Rosa Complex Central Terminal\n\tSanta Rosa Integrated Terminal (SRIT)\n\tBalibago - Sta. Cruz Van Terminal\n\tBalibago Transport Terminal - Sta. Rosa\n\tShuttle Service Terminal\n\tVan terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TRICYCLE TERMINAL": "Paseo De StaRosa\n\tTodap Terminal\n\tTricycle terminal"
    }
    return data

def fil_data()->dict:
    data = {
        "HOW ARE YOU": "Mabuti, Salamat sa pagtanong!",
        "INDUSTRIAL ESTATE WITHIN SANTA ROSA LAGUNA": "\nLaguna Technopark Inc.\nGreenfield Automotive Park.\nToyota Special Economic Zone.\nLakeside Evozone Nuvali.\nDaystar Santa Rosa Industrial Park.\nSanta Rosa Commercial Complex.\nMeridian Industrial Complex.",
        "SCHOOLS WITHIN SANTA ROSA LAGUNA": "\nColegio de Santa Rosa de Lima\nThe Canossa School, Inc. City of Santa Rosa, Laguna\nQueen Anne School of Sta. Rosa\nBlessed Christian School de Sta. Rosa\nHoly Rosary College of Santa Rosa, Laguna, Inc.\nMaranatha Living Hope Academy\nDila Elementary School\nFaithful Grace Christian School\nSanta Rosa Science and Technology High School\nDominican College of Santa Rosa\nBalibago Integrated High School\nSaint Ruiz Montessori School\nGreen Fields Integrated School of Laguna, Inc.\nOur Lady of Fatima University Sta. Rosa, Laguna\nSts. Paul & Mark School Inc\nMarie Margarette School\nSouthville 4 National High School\nJesus The Exalted Name School\nSanta Rosa Elementary School Central I HACIENDA DOMINICANO\nPolytechnic University of Philippines",
        "SIKHAYAN FESTIVAL": "\nAng Sikhayan Festival ay isang taunang pagdiriwang ng kultura sa Lungsod ng Santa Rosa, Laguna, Pilipinas. Ito ay isang pagdiriwang ng pagkakatatag ng lungsod at isang paraan upang parangalan ang mga tradisyon at pagmamalaki ng komunidad.",
        "SIKHAYAN MEANS MEANING OF SIGNIFY": "\nAng Sikhayan ay isang salitang Filipino na nangangahulugang \"sipag\" at \"kabuhayan\". Ito rin ang pangalan ng taunang pagdiriwang sa Santa Rosa, Laguna, Pilipinas. Ipinagdiriwang ng pagdiriwang ang mga tao ng Santa Rosa, ang kanilang espiritu ng pagnenegosyo, at ang kanilang katatagan.\nAng Sikhayan Festival ay nagmula sa sikap (hardwork) at kabuhayan (kabuhayan)",
        "THE HISTORY OF SIKHAYAN FESTIVAL": "\nIto ay inilunsad noong 2000 ni Mayor Leon Arcillas upang ipagdiwang ang makasaysayang simula ng Santa Rosa City bawat taon at isang paraan upang bigyan ng pagkilala ang mga tao, ang kanilang katatagan, at ang kanilang entrepreneurial spirit na nagtutulak sa patuloy na kaunlaran at paglago ng ekonomiya ng lungsod.",
        "SANTA ROSA LAGUNA IS KNOWN FOR": "\nAng Santa Rosa, Laguna ay kilala sa mga pang-industriyang estate nito, theme park, at Santa Rosa Arch.\nIsa sa dalawang pinakamalaking munisipalidad sa Laguna, ang Santa Rosa City, na kilala rin bilang Lion City of the South, ay matatagpuan sa kanluran ng Laguna de Bay.\nAng Sta Rosa ay pangunahing kilala para sa Coca-Cola at Toyota manufacturing plants sa mga industriyal na estate nito. Kamakailan ay naging sikat din ito sa pagiging site ng Enchanted Kingdom, isang lokal na theme park, pati na rin ang ilang pagpapaunlad ng pabahay. Ang Santa Rosa din ang exit traveller na dadaan sa South Luzon Expressway para pumunta sa Tagaytay at Taal Volcano. Ang lungsod na ito ay naglalaman ng ika-3 pinakamalaking complex sa Laguna, Paseo de Santa Rosa.",
        "WHY IS SANTA ROSA CITY CALLED THE LION CITY OF THE SOUTH": "\n\tIt is one of the Philippines’ fastest-growing economies. On March 10, 2004, the Philippine Congress approved Republic Act No. 9264, which made the city of Santa Rosa the first-class municipality from a fourth-class municipality. On July 10, 2004, Santa Rosa was proclaimed the country’s 101st city.\n\n\tThe city of Santa Rosa has made a name for itself in just three short years after it was transformed into a city and is now known for several economic triumphs. To put the City in the Billionaire’s Club among Philippine local government entities, the City’s 2007 income surpassed the one billion mark, from less than Php 600 million in 2003. Moreover, the flood of foreign and local investors interested in Santa Rosa has helped it treble its annual income during the last decade. Thus, making Santa Rosa the \“Lion City of the South.\”",
        "WHEN DID SANTA ROSA LAGUNA BECOME A CITY": "\n\tIsa ito sa pinakamabilis na lumalagong ekonomiya ng Pilipinas. Noong Marso 10, 2004, inaprubahan ng Kongreso ng Pilipinas ang Republic Act No. 9264, na nagtaas sa Santa Rosa mula sa isang ika-apat na klaseng bayan patungo sa unang klaseng lungsod. Noong Hulyo 10, 2004, idineklara ang Santa Rosa bilang ika-101 na lungsod ng bansa.\n\n\tNakilala ang lungsod ng Santa Rosa sa loob lamang ng tatlong taon matapos itong gawing lungsod at kilala na ngayon sa ilang mga tagumpay sa ekonomiya. Upang mailagay ang Lungsod sa Billionaire's Club sa mga lokal na pamahalaan ng Pilipinas, nalampasan ng kita nito noong 2007 ang isang bilyon, mula sa mas mababa sa Php 600 milyon noong 2003. Bukod pa rito, ang dagsa ng mga banyaga at lokal na mamumuhunan na interesado sa Santa Rosa ay nakatulong upang mapataas ng tatlong beses ang taunang kita nito sa nagdaang dekada. Kaya naman, tinawag ang Santa Rosa na \"Lion City of the South.\"",
        "TOTAL POPULATION OF SANTA ROSA LAGUNA": "\nAng populasyon nito batay sa Census noong 2020 ay 414,812. Ito ay kumakatawan sa 12.26% ng kabuuang populasyon ng lalawigan ng Laguna, o 2.56% ng kabuuang populasyon ng rehiyon ng CALABARZON.",
        "WHAT SIGNIFIES THE PLAZA IN SANTA ROSA LAGUNA": "\nAng plaza sa Santa Rosa, Laguna, Pilipinas, ay sumisimbolo sa kasaysayan, kultura, at pamana ng lungsod. Ang plaza ay nagtatampok ng monumento ni Jose Rizal na kumakatawan sa mga martir ng lungsod at ang kanilang pakikibaka para sa kalayaan.\n\nAno ang sinisimbolo ng plaza:\nKasaysayan: Ang plaza ay lugar ng pagbitay sa mga lokal na gerilya.\nKultura: Bahagi ang plaza ng sentrong kolonyal na Espanyol na ginagawang \"heritage square.\"\nPamana: Narito ang mga makasaysayang bahay at tanggapan ng pamahalaan.\nKalayaan: Ang monumento ni Jose Rizal ay sumasagisag sa mga martir ng lungsod at ang kanilang pakikibaka para sa kalayaan.",
        "WHAT DOES THE JOSE RIZAL MONUMENT SYMBOLIZE IN THE PLAZA OF SANTA ROSA LAGUNA": "\nMartiryo: Ang monumento ay sumasagisag sa pagsasakripisyo ng buhay para sa kalayaan.\nKarunungan: Ang monumento ay sumasagisag sa karunungan at katapangan ng mga taga-Santa Rosa.\nLiwanag laban sa kadiliman: Ang monumento ay sumasagisag sa ideya na ang liwanag ay laging mananaig sa kadiliman.",
        "WHO ESTABLISHED THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINE-SANTA ROSA CAMPUS": "\nItinatag ang Polytechnic University of the Philippines (PUP) Santa Rosa Campus ng Senado at Kapulungan ng mga Kinatawan ng Pilipinas sa pamamagitan ng Republic Act No. 11784. Kilala rin ang batas na ito bilang PUP-Santa Rosa Campus Act.",
        "WHO REQUESTED TO BUILD A BRANCH CAMPUS OF THE POLYTECHNIC UNIVERSITY OF THE PHILIPPINES IN SANTA ROSA, LAGUNA": "\nAng yumaong alkalde ng Santa Rosa, Laguna, Kgg. Leon C. Arcillas, ang humiling ng pagtatayo ng Polytechnic University of the Philippines (PUP) Santa Rosa Campus. Binuksan ang kampus noong 2003 at itinuturing na pamana ng mga pagsisikap ni Arcillas upang magbigay ng de-kalidad na edukasyon sa mga residente ng Santa Rosa at mga kalapit na bayan.\nOrihinal na itinatag ang Polytechnic University of the Philippines bilang Manila Business School noong 1904. Noong 1978, pinalitan ang pangalan ng Philippine College of Commerce (PCC) bilang PUP sa bisa ng Presidential Decree (PD) 1341.",
        "WHAT IS THE CHURCH'S NAME LOCATED BEHIND THE PLAZA OF SANTA ROSA LAGUNA": "\nSanta Rosa de Lima Parish Church",
        "WHEN WAS THE SANTA ROSA DE LIMA PARISH CHURCH BUILT": "\nAng Santa Rosa de Lima Parish Church sa Santa Rosa, Laguna, Pilipinas ay itinatag noong 1792. Itinayo ito ng paring Katolikong Kastila na si Francisco Favie.",
        "THE HISTORY OF THE SANTA ROSA DE LIMA PARISH CHURCH": "\nAng Santa Rosa de Lima Parish Church sa Santa Rosa, Laguna, Pilipinas ay itinayo noong 1792 ng paring Katolikong Kastila na si Francisco Favie. Ipinangalan ang simbahan kay Santa Rosa ng Lima, ang patrona ng Pilipinas, Amerika, at Silangang Indiya.\n\nPagkakatayo:\nAng simbahan at kumbento ay itinayo sa loob ng 12 taon\nAng kasalukuyang gusali ng simbahan ay itinayo noong 1796 ng mga paring Kastila na tumulong ang mga Tsinong manggagawa\nAng simbahan ay binasbasan noong Agosto 4, 1812\nAng unang Misa ay ginanap noong Agosto 30, 1812\n\nKasaysayan:\nBago itinayo ang simbahan, ang lugar ay tinawag na \"Bucol\"\nPinalitan ng mga residente ang pangalan ng lugar bilang \"Santa Rosa\" bilang parangal sa patrona\nAng orihinal na istruktura ay nananatili at kilala na ngayon bilang Museo de Santa Rosa\n\nSanta Rosa ng Lima\nSi Santa Rosa ng Lima ay ipinanganak bilang Isabel Flores de Oliva sa Lima, Peru noong 1586\nNakilala siya sa pagtulong sa mga may sakit at nagugutom sa kanyang komunidad\nBinigyan siya ng pangalang Rose ng isang kasambahay na nagsabing siya ay \"singganda ng isang rosas\"",
        "HISTORICAL TIMELINE OF SANTA ROSA LAGUNA": "\nAng makasaysayang timeline ng Santa Rosa, Laguna, Philippines ay kinabibilangan ng pananakop ng mga Espanyol, ang Himagsikang Pilipino, at ang panahon pagkatapos ng digmaan.\n1571: Natuklasan ng Espanyol na Conquistador na si Juan de Salcedo ang Biñan at isinama ito sa Tabuco\n1688: Nahiwalay ang Barrio Bukol mula sa Cabuyao\n1792: Naging munisipyo ang Barrio Bukol bilang Santa Rosa\n1812: Pinagpala ang Saint Rose of Lima Parish Church\n1859–1860: Itinayo ang Santa Rosa Arch upang palitan ang isang Espanyol na guard tower\n1898: Nagampanan ng Santa Rosa ang isang mahalagang papel sa Himagsikang Pilipino laban sa Espanya at lumagda sa Act of Independence\n1945: Nalaya ang Santa Rosa mula sa pananakop ng Hapon noong World War II\n1970s: Ang ekonomiya ng Santa Rosa ay nakabatay sa agrikultura at mga negosyong pag-aari ng pamilya\n1980s: Ang industriyalisasyon at pamumuhunan ng mga dayuhan ay nagbago sa ekonomiya at lipunan ng Santa Rosa\n2004: Naging lungsod ang Santa Rosa",
        "HISTORICAL HISTORY BACKGROUND OF SANTA ROSA LAGUNA": "\nAng Santa Rosa, Laguna, Philippines ay may mayamang kasaysayan na kinabibilangan ng papel nito sa Himagsikang Pilipino, ang panahon nito sa ilalim ng pananakop ng Hapon, at ang pag-unlad nito mula sa isang bayang agrikultural patungo sa isang modernong lungsod.\n\nMaagang kasaysayan\nBarrio Bukol\nNoong 1688, nahiwalay ang Barrio Bukol mula sa Cabuyao at naging bahagi ng Biñan.\n\nSaint Rose of Lima Parish Church\nNoong 1792, itinayo ng Espanyol na pari na si Francisco Favie ang Saint Rose of Lima Parish Church.\n\nMunicipality of Santa Rosa\nNoong 1792, naging sariling munisipyo ang Barrio Bukol at pinangalanan ito bilang Santa Rosa bilang parangal kay Saint Rose of Lima.\n\nAng papel ng Santa Rosa sa Himagsikang Pilipino\nAng Santa Rosa ay isang mahalagang lugar sa Himagsikang Pilipino laban sa mga Espanyol. Noong 1898, lumagda ang Santa Rosa sa Act of Independence, na nagproklama ng Kalayaan ng Pilipinas mula sa Espanya.\n\nWorld War II\nPananakop ng Hapon: Noong World War II, pansamantalang sinakop ng mga Hapon ang Santa Rosa.",
        "CALABARZON MEANING OF MEANS": "\nAng Calabarzon ay ang pangalan ng isang administratibong rehiyon sa Pilipinas na binubuo ng limang lalawigan: Cavite, Laguna, Batangas, Rizal, at Quezon. Ang pangalan ay isang acronym ng unang titik ng bawat lalawigan.",
        "WHY IS IT CALLED CALABARZON": "\nAng rehiyon ay nilikha upang pagsamahin ang panlipunan at pang-ekonomiyang pag-unlad ng limang lalawigan.\nKilala rin ito bilang Region IV-A.",
        "IN WHAT ASPECT IS CALABARZON KNOWN": "\nAng Calabarzon ay kilala bilang industrial powerhouse ng Pilipinas.\nTahanan ito ng marami sa mga pinakamataong lalawigan ng bansa.\nIto ang lugar ng kapanganakan ng kalayaan ng Pilipinas mula sa Espanya noong 1898.\nIto ang lugar ng kapanganakan ng mga pambansang bayani tulad ni Jose Rizal.\nTahanan ito ng maraming tradisyong pangkultura, kabilang ang pag-ukit ng kahoy at taka (papier-mâché).",
        "WHAT IS THE RANKING POSITION OF SANTA ROSA, LAGUNA WHEN IT COMES TO ITS RANKING AMONG NEARBY CITIES IN THE ENTIRE COUNTRY": "\nAng Santa Rosa, Laguna ay isang prominenteng lungsod sa Pilipinas, at itinuturing na pinakamayamang lungsod sa Luzon sa labas ng Metro Manila. Isa rin ito sa pinakamabilis na lumalagong ekonomiya sa bansa.\n\nRanking:\nNoong 2019, niranggo ang Santa Rosa bilang pangatlo sa bansa para sa kahusayan nito sa pagkolekta ng lokal na kita.\nNoong 2022, nagkaroon ang Santa Rosa ng pinakamataas na kita sa anumang lokal na pamahalaan (LGU) sa Laguna.",
        "WHERE WAS DR. JOSE RIZAL BORN": "\nCalamba, Laguna",
        "WHEN WAS DR. JOSE RIZAL BORN": "\nHunyo 19, 1861",
        "WHAT IS THE FULL NAME OF DR. JOSE RIZAL": "\nJose Protacio Rizal Mercado y Alonso Realonda",
        "WHO ARE THE PARENTS OF DR. JOSE RIZAL": "\nFrancisco Mercado at Teodora Alonso Realonda",
        "WHO IS THE FATHER OF DR. JOSE RIZAL": "\nFrancisco Mercado ",
        "WHO IS THE MOTHER OF DR. JOSE RIZAL": "\nTeodora Alonso Realonda",
        "NATURE ATTRACTION IN LAGUNA": "\nPagsanjan Falls\nHulugan Falls\nHidden Valley Falls\nTaytay Falls\nLake Pandin\nMount Makiling\nSampaloc Lake\nMt. Banahaw\nLake Yambo\nBangking Kahoy Valley\nLake Caliraya\nMakiling Botanic Gardens\nBukal Falls\nJapanese Garden\nDalitiwan River\nPanguil River Eco Park\nMount Kalisungan\nCavinti Underground River and Caves Complex\nTayak Hill\nBunga Falls\nMt. Romelo\nBuntot Palos Falls\nKalayaan Twin Falls\nBuruwisan Falls\nPueblo El Salvador Nature’s Park and Picnic Grove\nMagdalena White Water River\nLake Palakpakin\nLake Calibato\nLake Bunot\nLake Muhikap\nHilabaan Island",
        "HISTORICAL PLACES IN SANTA ROSA, LAGUNA": "\nCuartel De Sto. Domingo\nSanta Rosa De Lima Parish Church\nMuseo De Santa Rosa\nCity Plaza\nSanta Rosa Arch",
        "LOCAL HERITAGE IN BIÑAN LAGUNA": "\nSite of Historic Alberto Mansion\nSentrong Pangkultura ng Biñan (Old Municipal Building)\nSchool of Rizal Site and Museum\nSan Isidro Labrador Catholic Church\nVicente Ocampo House\nJose Rizal Monument\nLos Maduros Bandstand\nFrancisco Almeda House\nCasa Biñanese – Jacobo Gonzales House\nJacinto Francisco House\nFilomena Belizario Hernandez House\nAlberto Yaptinchay House\nPedro-Isidro Cariño Isidro House\nIluminado Valencia House\nBiñan Roman Catholic Cemetery Camposanto\nCasa Paroquial-Biñan Cursillo House\nGabaldon Building of Biñan Elementary School\nCapilla De San Jose\nOld Binyang PNR Station including its Office and Railway\nBiñan Municipal Cemetery\nFrancisco Baylon House\nFrancisco Guico House\nTeodora Velasco House\nLaureano Cariño House\nIsisdro Gonzalez House\nSoro-soro Prinza Dam\nHistoric Alberto Mansion",
        "BARANGAYS IN SANTA ROSA LAGUNA": "\nMay labing-walo (18) na barangay na matatagpuan sa Santa Rosa, Laguna. Ang mga sumusunod ay ang labing-walo (18) na barangay:\nAplaya\nBalibago\nCaingin\nDila\nDita\nDon Jose\nIbaba\nKanluran\nLabas\nMacabling\nMalitlit\nMalusak\nMarket Area\nPooc\nPulong Santa Cruz\nSanto Domingo\nSinalhan\nTagapo",
        "WHAT ARE THE ATTRACTIONS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN SANTA ROSA LAGUNA": "\nAng Santa Rosa City ay may maraming atraksyon na tiyak na magdudulot ng kasiyahan hindi lamang sa mga turista, kundi pati na rin sa mga mamamayan nito. Ito ang mga atraksyon na maiaalok ng Lion City of the South — Santa Rosa, Laguna:\n\nTheme Park\nEnchanted Kingdom\n\nShopping Centers\nSM City Santa Rosa\nRobinson's Mall\nAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\nWalterMart\nVictory Mall\nTarget Mall\nWest Borrough Town Center\nPaseo de Santa Rosa\nEton City Square\n\nFarms\nFun Farm at Sta. Elena\nHoly Carabao\n\nParks\nNuvali Park\nSanta Rosa's City Plaza\n\nResorts and Events Place\nDictado 1\nDictado 2\nDictado 3\nSouthpick Resort\nCalypso Resort Hotel\nCarvill Private Resort\nCesar's Cabin Private Resort\nCriselda Private Resort\nPopong's Bukid Private Resort\nOlive's Private Resort\nBayani Resort\nKyler and Kean Private Resort\nCasa Vallejo Events Place and Private Resort\nNMV Resort Farmview\nLas Asturias\nVilla Gilda Resort\nSherinai Events Place\nSouth Country Garden\nLouLyn's Resort\nPablo's Events Place\nMarigold's Farm Resort\nTAR's Family and  Private Resort\nBay View Resort\n\nHotels / Motels\nSeda Nuvali\nPaseo Premiere Hotel\nAsiatel Inn\nTechopark Hotel\nMicrotel\nEl Cielito Hotel\nCasa Emerita\nCandy Motel\nHotel Sogo\nMariposa Hotel\n\nOthers(Sta. Elena's Golf and Country Club)",
        "SHOPPING MALLS IN SANTA ROSA LAGUNA": "\nIto ang listahan ng mga Shopping Centers sa Santa Rosa:\nSM City Santa Rosa\nRobinson's Mall\nAyala Malls (Solenad, Solenad 1, Solenad 3, Solenad 4)\nWalterMart\nVictory Mall\nTarget Mall\nWest Borrough Town Center\nPaseo de Santa Rosa\nEton City Square",
        "RESORTS AND EVENTS PLACE IN SANTA ROSA LAGUNA": "\nMayroong maraming pribado at pampublikong resorts at events place sa Santa Rosa, at kabilang dito ang:\nSouthpick Resort\nDictado 1\nDictado 2\nDictado 3\nCalypso Resort Hotel\nCarvill Private Resort\nCesar's Cabin Private Resort\nCriselda Private Resort\nPopong's Bukid Private Resort\nOlive's Private Resort\nKyler and Kean Private Resort\nCasa Vallejo Events Place and Private Resort\nNMV Resort Farmview\nLas Asturias\nVilla Gilda Resort\nBayani Resort\nSherinai Events Place\nSouth Country Garden\nLouLyn's Resort\nPablo's Events Place\nMarigold's Farm Resort\nTAR's Family and  Private Resort\nBay View Resort",
        "PARKS IN SANTA ROSA LAGUNA": "\nSa kasalukuyan, may dalawa (2) na available na parke sa Santa Rosa, at ito ang mga sumusunod:\nNuvali Park\nSanta Rosa's City Plaza",
        "THEME PARK IN SANTA ROSA": "\nAng Enchanted Kingdom, na kilala rin bilang EK, ay ang tanging theme park na matatagpuan sa Santa Rosa, kilala ito sa maraming masaya at nakakakilig na rides na maiaalok nito, pati na rin sa mga developed lot spaces na sinasakop nito.",
        "HOTELS OR MOTELS IN SANTA ROSA": "\nIto ang ilan sa mga Hotels, o Motels, na sikat sa lungsod:\nSeda Nuvali\nPaseo Premiere Hotel\nAsiatel Inn\nTechopark Hotel\nMicrotel\nEl Cielito Hotel\nCasa Emerita\nCandy Motel\nHotel Sogo\nMariposa Hotel",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY POOC": "\nSa kabuuan, may limang (5) resorts na matatagpuan sa Barangay Pooc, at ito ang mga sumusunod:\nCarvill Private Resort\nCriselda Private Resort\nPopong's Bukid Private Resort\nOlive's Private Resort\nKyler and Kean Private Resort\n\nAng mga nabanggit na resorts ay matatagpuan sa Caramay Compound, La Concordia, Barangay Pooc, City of Santa Rosa, Laguna.",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY MARKET AREA": "\nAng Barangay Market Area ay may limang (5) resorts na maiaalok, at ito ay:\nSouthpick Resort\nPablo's Events Place\nDictado 1\nDictado 2\nDictado 3",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY SINALHAN": "\nSa kasalukuyan, walang resorts na matatagpuan sa Barangay Sinalhan",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY TAGAPO": "\nIto ang mga resort na maiaalok ng Barangay Tagapo:\nLouLyn's Resort\nTAR's Family and Private Resort\nNMV Resort\nSherinai Events Place\nMarigold's Farm Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY IBABA": "\nIto ang tanging resort na maiaalok ng Barangay Ibaba:\nCasa Vallejo Events Place and Private Resort",
        "RESORTS THAT CAN FOUND LOCATE LOCATED LOCATION OF IN BARANGAY CAINGIN": "\nIto ang tanging resorts na maiaalok ng Barangay Caingin:\nVilla Gilda Resort\nBayani Resort",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED LOCATION OF IN BARANGAY DITA": "\nIto ang tanging resort na matatagpuan sa Barangay Dita:\nSouth Country Garden",
        "RESORTS THAT CAN BE FOUND LOCATE LOCATED IN BARANGAY MACABLING": "\nAng tanging resort na matatagpuan sa Barangay Macabling ay:\nCalypso Resort ",
        "EMERGENCY SERVICES": "\nSt. James Hospital\nSanta Rosa Community Hospital\nNew Sinai MD Hospital\nThe Medical City South Luzon\nUnihealth Santa Rosa Hospital and Medical Center\nMarian Hospital\nCity Medic Emergency Hospital\nBalibago Polyclinic and Hospital, Inc.\nSanta Rosa Hospital and Medical Center\nHealthway QualiMed Hospital Santa Rosa\nThe Medical City, South Luzon",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TERMINAL": "\nSta. Rosa Complex Central Terminal\nSanta Rosa Integrated Terminal (SRIT)\nBBL Bus Terminal\nBalibago - Sta. Cruz Van Terminal\nBalibago Transport Terminal - Sta. Rosa\nAlabang Express Jeepney Terminal\nShuttle Service Terminal\nVan terminal\nJAM Bus Terminal\nPaseo De StaRosa\nUBE Express - Robinsons Sta. Rosa\nJam Liner Bus Stop\nTodap Terminal\nBBPL Transport Terminal\nBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\nPaseo de Sta Rosa - Calamba Jeepney Terminal\nJam Transit Inc. Terminal - Penta\nTricycle terminal\nHM Terminal-Target\nNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A JEEPNEY TERMINAL": "\nSta. Rosa Complex Central Terminal\nBalibago Transport Terminal - Sta. Rosa\nAlabang Express Jeepney Terminal\nPaseo De StaRosa\nBalibago (Sta Rosa) - (Ulat)Tagaytay City Jeepney Terminal\nPaseo de Sta Rosa - Calamba Jeepney Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A BUS TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBBL Bus Terminal\n\t\tShuttle Service Terminal\n\t\tJAM Bus Terminal\n\t\tUBE Express - Robinsons Sta. Rosa\n\t\tJam Liner Bus Stop\n\t\tBBPL Transport Terminal\n\t\tJam Transit Inc. Terminal - Penta\n\t\tHM Terminal-Target\n\t\tNuvali Transport Terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A VAN TERMINAL": "  Sta. Rosa Complex Central Terminal\n\t\tSanta Rosa Integrated Terminal (SRIT)\n\t\tBalibago - Sta. Cruz Van Terminal\n\t\tBalibago Transport Terminal - Sta. Rosa\n\t\tShuttle Service Terminal\n\t\tVan terminal",
        "WHERE CAN I FIND LOCATE LOCATED LOCATION OF A TRICYCLE TERMINAL": "  Paseo De StaRosa\n\t\tTodap Terminal\n\t\tTricycle terminal"
    }
    return data

def reply(sentence: str, data: dict)->None:
    compare: dict = {key: 0 for key in data.keys()} # Will start at 0 and For every key/question in data
        
    input_words = set(sentence.split()) # Converted to set to efficiently handles matching, and split keys in the data
                                        # input_words is a set of word per word from self.sentence/from the input of the user
    for key, responses in data.items():
        key_words = set(key.split()) # key_word is a set of word per word from each key in data
        compare[key] = len(input_words & key_words)  # This will match how many words match in input_words & key_words using &/ intersection operator

    highest_value = max(compare.values())

    if highest_value == 0: # No match, highest matches does not have any element and is equal to 0
        print("AskSantaRosa: I'm sorry, I don't understand that.")
        return

    matching_keys = [k for k, v in compare.items() if v == highest_value] # Will look for the keys in compare that will match the value of highest_matches
    if len(matching_keys) == 1: # If it is only 1 match
        print(f"AskSantaRosa: {data[matching_keys[0]]}")
    else:
        # If their is a tie, the first match will be picked
        print(f"AskSantaRosa: {data[matching_keys[0]]}")

def main()->None:
    language = main_introduction()
    while True:
        if language == "FILIPINO" :
            sentence = user_input_fil()
            data = fil_data()
        else:
            sentence = user_input_EN()
            data = en_data()
        if sentence == 'EXIT':
            print("AskSantaRosa: Thank you for chatting with me!")
            break
        reply(sentence.upper(), data)

if __name__ == '__main__':
    main()